=== hostedposted/PokemonData/data/schema/pokemon/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "capture_rate": {
      "type": "integer"
    },
    "color": {
      "type": "string"
    },
    "damage_multipliers": {
      "type": "object",
      "properties": {
        "normal": {
          "type": "integer"
        },
        "fire": {
          "type": "integer"
        },
        "water": {
          "type": "integer"
        },
        "electric": {
          "type": "integer"
        },
        "grass": {
          "type": "integer"
        },
        "ice": {
          "type": "integer"
        },
        "fighting": {
          "type": "integer"
        },
        "poison": {
          "type": "integer"
        },
        "ground": {
          "type": "integer"
        },
        "flying": {
          "type": "integer"
        },
        "psychic": {
          "type": "integer"
        },
        "bug": {
          "type": "integer"
        },
        "rock": {
          "type": "integer"
        },
        "ghost": {
          "type": "integer"
        },
        "dragon": {
          "type": "integer"
        },
        "dark": {
          "type": "integer"
        },
        "steel": {
          "type": "integer"
        },
        "fairy": {
          "type": "integer"
        }
      },
      "required": [
        "bug",
        "dark",
        "dragon",
        "electric",
        "fairy",
        "fighting",
        "fire",
        "flying",
        "ghost",
        "grass",
        "ground",
        "ice",
        "normal",
        "poison",
        "psychic",
        "rock",
        "steel",
        "water"
      ]
    },
    "description": {
      "type": [
        "null",
        "string"
      ]
    },
    "egg_groups": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "evolution_chain": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "evolves_from_species": {
      "type": [
        "null",
        "string"
      ]
    },
    "growth_rate": {
      "type": "string"
    },
    "height": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "is_baby": {
      "type": "boolean"
    },
    "is_legendary": {
      "type": "boolean"
    },
    "is_mythical": {
      "type": "boolean"
    },
    "moves": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "tm": {
            "type": "boolean"
          },
          "level": {
            "type": [
              "integer",
              "null"
            ]
          }
        },
        "required": [
          "level",
          "name",
          "tm"
        ]
      }
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "object",
      "properties": {
        "french": {
          "type": "string"
        },
        "german": {
          "type": "string"
        },
        "spanish": {
          "type": "string"
        },
        "italian": {
          "type": "string"
        },
        "english": {
          "type": "string"
        },
        "japanese": {
          "type": "string"
        }
      },
      "required": [
        "english",
        "french",
        "german",
        "italian",
        "japanese",
        "spanish"
      ]
    },
    "pokedex_numbers": {
      "type": "object",
      "properties": {
        "national": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-central": {
          "type": [
            "integer",
            "null"
          ]
        },
        "isle-of-armor": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "conquest-gallery": {
          "type": [
            "integer",
            "null"
          ]
        },
        "galar": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-unova": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-mountain": {
          "type": [
            "integer",
            "null"
          ]
        },
        "hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "extended-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-coastal": {
          "type": [
            "integer",
            "null"
          ]
        },
        "crown-tundra": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-unova": {
          "type": [
            "integer",
            "null"
          ]
        }
      }
    },
    "region": {
      "type": "string"
    },
    "region_id": {
      "type": "integer"
    },
    "shape": {
      "type": "string"
    },
    "species": {
      "type": "string"
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "shiny": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "shiny"
      ]
    },
    "stats": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "base_stat": {
            "type": "integer"
          }
        },
        "required": [
          "base_stat",
          "name"
        ]
      }
    },
    "types": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "url"
        ]
      }
    },
    "weight_kilograms": {
      "type": "integer"
    },
    "weight_pounds": {
      "type": "integer"
    }
  }
}

=== hostedposted/PokemonData/data/api/pokemon/blacephalon/index.json
{
  "abilities": [
    {
      "name": "beast-boost",
      "url": "https://thepokeapi.com/ability/beast-boost",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "capture_rate": 30,
  "color": "white",
  "damage_multipliers": {
    "normal": 0,
    "fire": 0,
    "water": 2,
    "electric": 1,
    "grass": 0,
    "ice": 0,
    "fighting": 0,
    "poison": 0,
    "ground": 2,
    "flying": 1,
    "psychic": 1,
    "bug": 0,
    "rock": 2,
    "ghost": 2,
    "dragon": 1,
    "dark": 2,
    "steel": 0,
    "fairy": 0
  },
  "description": "A UB that appeared from an Ultra Wormhole, it causes explosions, then takes advantage of opponents\u2019 surprise to rob them of their vitality.",
  "egg_groups": [
    "no-eggs"
  ],
  "evolution_chain": [
    [
      "blacephalon"
    ]
  ],
  "evolves_from_species": null,
  "growth_rate": "slow",
  "height": 71,
  "id": 806,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "ember",
      "level": 1,
      "tm": false
    },
    {
      "name": "flamethrower",
      "tm": true,
      "level": null
    },
    {
      "name": "hyper-beam",
      "tm": true,
      "level": null
    },
    {
      "name": "toxic",
      "tm": true,
      "level": null
    },
    {
      "name": "psychic",
      "tm": true,
      "level": null
    },
    {
      "name": "night-shade",
      "level": 23,
      "tm": false
    },
    {
      "name": "double-team",
      "tm": true,
      "level": null
    },
    {
      "name": "light-screen",
      "level": 29,
      "tm": false
    },
    {
      "name": "fire-blast",
      "level": 37,
      "tm": false
    },
    {
      "name": "explosion",
      "tm": true,
      "level": null
    },
    {
      "name": "rest",
      "tm": true,
      "level": null
    },
    {
      "name": "substitute",
      "tm": true,
      "level": null
    },
    {
      "name": "thief",
      "tm": true,
      "level": null
    },
    {
      "name": "protect",
      "tm": true,
      "level": null
    },
    {
      "name": "swagger",
      "tm": true,
      "level": null
    },
    {
      "name": "sleep-talk",
      "tm": true,
      "level": null
    },
    {
      "name": "return",
      "tm": true,
      "level": null
    },
    {
      "name": "frustration",
      "tm": true,
      "level": null
    },
    {
      "name": "hidden-power",
      "tm": true,
      "level": null
    },
    {
      "name": "sunny-day",
      "tm": true,
      "level": null
    },
    {
      "name": "shadow-ball",
      "level": 41,
      "tm": false
    },
    {
      "name": "torment",
      "tm": true,
      "level": null
    },
    {
      "name": "will-o-wisp",
      "tm": true,
      "level": null
    },
    {
      "name": "facade",
      "tm": true,
      "level": null
    },
    {
      "name": "taunt",
      "tm": true,
      "level": null
    },
    {
      "name": "trick",
      "level": 47,
      "tm": false
    },
    {
      "name": "magic-coat",
      "level": 7,
      "tm": false
    },
    {
      "name": "astonish",
      "level": 1,
      "tm": false
    },
    {
      "name": "overheat",
      "tm": true,
      "level": null
    },
    {
      "name": "calm-mind",
      "level": 31,
      "tm": false
    },
    {
      "name": "payback",
      "tm": true,
      "level": null
    },
    {
      "name": "fling",
      "tm": true,
      "level": null
    },
    {
      "name": "dark-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "shadow-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "psyshock",
      "tm": true,
      "level": null
    },
    {
      "name": "smack-down",
      "tm": true,
      "level": null
    },
    {
      "name": "flame-burst",
      "level": 17,
      "tm": false
    },
    {
      "name": "flame-charge",
      "tm": true,
      "level": null
    },
    {
      "name": "round",
      "tm": true,
      "level": null
    },
    {
      "name": "stored-power",
      "level": 13,
      "tm": false
    },
    {
      "name": "quash",
      "tm": true,
      "level": null
    },
    {
      "name": "confide",
      "tm": true,
      "level": null
    },
    {
      "name": "mind-blown",
      "level": 59,
      "tm": false
    }
  ],
  "name": "blacephalon",
  "names": {
    "french": "Pierroteknik",
    "german": "Kopplosio",
    "spanish": "Blacephalon",
    "italian": "Blacephalon",
    "english": "Blacephalon",
    "japanese": "\u30ba\u30ac\u30c9\u30fc\u30f3"
  },
  "pokedex_numbers": {
    "national": {
      "id": 806,
      "url": "https://thepokeapi.com/pokedex/national"
    },
    "updated-alola": {
      "id": 393,
      "url": "https://thepokeapi.com/pokedex/updated-alola"
    },
    "kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kanto"
    },
    "original-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-johto"
    },
    "updated-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-johto"
    },
    "kalos-central": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-central"
    },
    "isle-of-armor": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/isle-of-armor"
    },
    "updated-kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-kanto"
    },
    "conquest-gallery": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/conquest-gallery"
    },
    "galar": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/galar"
    },
    "original-alola": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-alola"
    },
    "original-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-melemele"
    },
    "original-akala": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-akala"
    },
    "updated-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-melemele"
    },
    "updated-akala": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-akala"
    },
    "updated-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-unova"
    },
    "original-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-ulaula"
    },
    "original-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-poni"
    },
    "updated-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-ulaula"
    },
    "updated-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-poni"
    },
    "kalos-mountain": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-mountain"
    },
    "hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/hoenn"
    },
    "original-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-sinnoh"
    },
    "extended-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/extended-sinnoh"
    },
    "updated-hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-hoenn"
    },
    "kalos-coastal": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-coastal"
    },
    "crown-tundra": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/crown-tundra"
    },
    "original-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-unova"
    }
  },
  "region": "alola",
  "region_id": 7,
  "shape": "humanoid",
  "species": "Fireworks Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/806.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/806.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 53
    },
    {
      "name": "attack",
      "base_stat": 127
    },
    {
      "name": "defense",
      "base_stat": 53
    },
    {
      "name": "special-attack",
      "base_stat": 151
    },
    {
      "name": "special-defense",
      "base_stat": 79
    },
    {
      "name": "speed",
      "base_stat": 107
    }
  ],
  "types": [
    {
      "name": "fire",
      "url": "https://thepokeapi.com/type/fire"
    },
    {
      "name": "ghost",
      "url": "https://thepokeapi.com/type/ghost"
    }
  ],
  "weight_kilograms": 13,
  "weight_pounds": 29
}

=== hostedposted/PokemonData/data/api/pokemon/eiscue-ice/index.json
{
  "abilities": [
    {
      "name": "ice-face",
      "url": "https://thepokeapi.com/ability/ice-face",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "capture_rate": 60,
  "color": "blue",
  "damage_multipliers": {
    "normal": 1,
    "fire": 4,
    "water": 1,
    "electric": 1,
    "grass": 0,
    "ice": 0,
    "fighting": 1,
    "poison": 1,
    "ground": 0,
    "flying": 2,
    "psychic": 1,
    "bug": 1,
    "rock": 4,
    "ghost": 1,
    "dragon": 1,
    "dark": 1,
    "steel": 2,
    "fairy": 1
  },
  "description": "This Pok\u00e9mon keeps its heat-sensitive head cool with ice. It fishes for its food, dangling its single hair into the sea to lure in prey.",
  "egg_groups": [],
  "evolution_chain": [
    [
      "eiscue"
    ]
  ],
  "evolves_from_species": null,
  "growth_rate": "slow",
  "height": 55,
  "id": 875,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "powder snow",
      "level": 1,
      "tm": false
    },
    {
      "name": "tackle",
      "level": 1,
      "tm": false
    },
    {
      "name": "mist",
      "level": 6,
      "tm": false
    },
    {
      "name": "weather ball",
      "level": 12,
      "tm": false
    },
    {
      "name": "icy wind",
      "level": 18,
      "tm": false
    },
    {
      "name": "headbutt",
      "level": 24,
      "tm": false
    },
    {
      "name": "amnesia",
      "level": 30,
      "tm": false
    },
    {
      "name": "freeze-dry",
      "level": 36,
      "tm": false
    },
    {
      "name": "hail",
      "level": 42,
      "tm": false
    },
    {
      "name": "aurora veil",
      "level": 48,
      "tm": false
    },
    {
      "name": "surf",
      "level": 54,
      "tm": false
    },
    {
      "name": "blizzard",
      "level": 60,
      "tm": false
    },
    {
      "name": "soak",
      "tm": false,
      "level": null
    },
    {
      "name": "aqua ring",
      "tm": false,
      "level": null
    },
    {
      "name": "belly drum",
      "tm": false,
      "level": null
    },
    {
      "name": "double-edge",
      "tm": false,
      "level": null
    },
    {
      "name": "icicle crash",
      "tm": false,
      "level": null
    },
    {
      "name": "head smash",
      "tm": false,
      "level": null
    },
    {
      "name": "dynamic-punch",
      "tm": true,
      "level": null
    },
    {
      "name": "work-up",
      "tm": true,
      "level": null
    },
    {
      "name": "headbutt",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "curse",
      "tm": true,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "psyshock",
      "tm": true,
      "level": null
    },
    {
      "name": "whirlwind",
      "tm": true,
      "level": null
    },
    {
      "name": "calm-mind",
      "tm": true,
      "level": null
    },
    {
      "name": "roar",
      "tm": true,
      "level": null
    }
  ],
  "name": "eiscue-ice",
  "names": {
    "french": "Bekagla\u00e7on",
    "german": "Kubuin",
    "spanish": "Eiscue",
    "italian": "Eiscue",
    "english": "Eiscue",
    "japanese": "\u30b3\u30aa\u30ea\u30c3\u30dd"
  },
  "pokedex_numbers": {
    "national": 875,
    "galar": 370,
    "crown-tundra": 90,
    "kanto": null,
    "original-johto": null,
    "updated-johto": null,
    "kalos-central": null,
    "isle-of-armor": null,
    "updated-kanto": null,
    "conquest-gallery": null,
    "original-alola": null,
    "original-melemele": null,
    "original-akala": null,
    "updated-alola": null,
    "updated-melemele": null,
    "updated-akala": null,
    "updated-unova": null,
    "original-ulaula": null,
    "original-poni": null,
    "updated-ulaula": null,
    "updated-poni": null,
    "kalos-mountain": null,
    "hoenn": null,
    "original-sinnoh": null,
    "extended-sinnoh": null,
    "updated-hoenn": null,
    "kalos-coastal": null,
    "original-unova": null
  },
  "region": "galar",
  "region_id": 8,
  "shape": "upright",
  "species": "Penguin Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/875.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/875.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 75
    },
    {
      "name": "attack",
      "base_stat": 80
    },
    {
      "name": "defense",
      "base_stat": 110
    },
    {
      "name": "special-attack",
      "base_stat": 65
    },
    {
      "name": "special-defense",
      "base_stat": 90
    },
    {
      "name": "speed",
      "base_stat": 50
    }
  ],
  "types": [
    {
      "name": "ice",
      "url": "https://thepokeapi.com/type/ice"
    }
  ],
  "weight_kilograms": 89,
  "weight_pounds": 196
}
