=== hostedposted/PokemonData/data/schema/pokemon/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "capture_rate": {
      "type": "integer"
    },
    "color": {
      "type": "string"
    },
    "damage_multipliers": {
      "type": "object",
      "properties": {
        "normal": {
          "type": "integer"
        },
        "fire": {
          "type": "integer"
        },
        "water": {
          "type": "integer"
        },
        "electric": {
          "type": "integer"
        },
        "grass": {
          "type": "integer"
        },
        "ice": {
          "type": "integer"
        },
        "fighting": {
          "type": "integer"
        },
        "poison": {
          "type": "integer"
        },
        "ground": {
          "type": "integer"
        },
        "flying": {
          "type": "integer"
        },
        "psychic": {
          "type": "integer"
        },
        "bug": {
          "type": "integer"
        },
        "rock": {
          "type": "integer"
        },
        "ghost": {
          "type": "integer"
        },
        "dragon": {
          "type": "integer"
        },
        "dark": {
          "type": "integer"
        },
        "steel": {
          "type": "integer"
        },
        "fairy": {
          "type": "integer"
        }
      },
      "required": [
        "bug",
        "dark",
        "dragon",
        "electric",
        "fairy",
        "fighting",
        "fire",
        "flying",
        "ghost",
        "grass",
        "ground",
        "ice",
        "normal",
        "poison",
        "psychic",
        "rock",
        "steel",
        "water"
      ]
    },
    "description": {
      "type": [
        "null",
        "string"
      ]
    },
    "egg_groups": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "evolution_chain": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "evolves_from_species": {
      "type": [
        "null",
        "string"
      ]
    },
    "growth_rate": {
      "type": "string"
    },
    "height": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "is_baby": {
      "type": "boolean"
    },
    "is_legendary": {
      "type": "boolean"
    },
    "is_mythical": {
      "type": "boolean"
    },
    "moves": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "tm": {
            "type": "boolean"
          },
          "level": {
            "type": [
              "integer",
              "null"
            ]
          }
        },
        "required": [
          "level",
          "name",
          "tm"
        ]
      }
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "object",
      "properties": {
        "french": {
          "type": "string"
        },
        "german": {
          "type": "string"
        },
        "spanish": {
          "type": "string"
        },
        "italian": {
          "type": "string"
        },
        "english": {
          "type": "string"
        },
        "japanese": {
          "type": "string"
        }
      },
      "required": [
        "english",
        "french",
        "german",
        "italian",
        "japanese",
        "spanish"
      ]
    },
    "pokedex_numbers": {
      "type": "object",
      "properties": {
        "national": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-central": {
          "type": [
            "integer",
            "null"
          ]
        },
        "isle-of-armor": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "conquest-gallery": {
          "type": [
            "integer",
            "null"
          ]
        },
        "galar": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-unova": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-mountain": {
          "type": [
            "integer",
            "null"
          ]
        },
        "hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "extended-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-coastal": {
          "type": [
            "integer",
            "null"
          ]
        },
        "crown-tundra": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-unova": {
          "type": [
            "integer",
            "null"
          ]
        }
      }
    },
    "region": {
      "type": "string"
    },
    "region_id": {
      "type": "integer"
    },
    "shape": {
      "type": "string"
    },
    "species": {
      "type": "string"
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "shiny": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "shiny"
      ]
    },
    "stats": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "base_stat": {
            "type": "integer"
          }
        },
        "required": [
          "base_stat",
          "name"
        ]
      }
    },
    "types": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "url"
        ]
      }
    },
    "weight_kilograms": {
      "type": "integer"
    },
    "weight_pounds": {
      "type": "integer"
    }
  }
}

=== hostedposted/PokemonData/data/api/pokemon/700/index.json
{
  "abilities": [
    {
      "name": "cute-charm",
      "url": "https://thepokeapi.com/ability/cute-charm",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "pixilate",
      "url": "https://thepokeapi.com/ability/pixilate",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "capture_rate": 45,
  "color": "pink",
  "damage_multipliers": {
    "normal": 1,
    "fire": 2,
    "water": 1,
    "electric": 1,
    "grass": 1,
    "ice": 0,
    "fighting": 1,
    "poison": 2,
    "ground": 1,
    "flying": 1,
    "psychic": 1,
    "bug": 0,
    "rock": 2,
    "ghost": 1,
    "dragon": 0,
    "dark": 0,
    "steel": 4,
    "fairy": 1
  },
  "description": "Sylveon wraps its ribbonlike feelers around its Trainer\u2019s arm because this touch enables it to read its Trainer\u2019s feelings.",
  "egg_groups": [
    "ground"
  ],
  "evolution_chain": [
    [
      "eevee"
    ],
    [
      "vaporeon",
      "jolteon",
      "flareon",
      "espeon",
      "umbreon",
      "leafeon",
      "glaceon",
      "sylveon"
    ]
  ],
  "evolves_from_species": "eevee",
  "growth_rate": "medium",
  "height": 39,
  "id": 700,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "cut",
      "tm": true,
      "level": null
    },
    {
      "name": "sand-attack",
      "level": 5,
      "tm": false
    },
    {
      "name": "tackle",
      "level": 1,
      "tm": false
    },
    {
      "name": "tail-whip",
      "level": 1,
      "tm": false
    },
    {
      "name": "hyper-beam",
      "tm": true,
      "level": null
    },
    {
      "name": "dig",
      "tm": true,
      "level": null
    },
    {
      "name": "toxic",
      "tm": true,
      "level": null
    },
    {
      "name": "quick-attack",
      "level": 13,
      "tm": false
    },
    {
      "name": "double-team",
      "tm": true,
      "level": null
    },
    {
      "name": "light-screen",
      "level": 33,
      "tm": false
    },
    {
      "name": "reflect",
      "tm": true,
      "level": null
    },
    {
      "name": "swift",
      "level": 17,
      "tm": false
    },
    {
      "name": "flash",
      "tm": true,
      "level": null
    },
    {
      "name": "rest",
      "tm": true,
      "level": null
    },
    {
      "name": "substitute",
      "tm": true,
      "level": null
    },
    {
      "name": "snore",
      "level": 0,
      "tm": false
    },
    {
      "name": "protect",
      "tm": true,
      "level": null
    },
    {
      "name": "swagger",
      "tm": true,
      "level": null
    },
    {
      "name": "attract",
      "tm": true,
      "level": null
    },
    {
      "name": "sleep-talk",
      "tm": true,
      "level": null
    },
    {
      "name": "heal-bell",
      "level": 0,
      "tm": false
    },
    {
      "name": "return",
      "tm": true,
      "level": null
    },
    {
      "name": "frustration",
      "tm": true,
      "level": null
    },
    {
      "name": "safeguard",
      "tm": true,
      "level": null
    },
    {
      "name": "iron-tail",
      "level": 0,
      "tm": false
    },
    {
      "name": "hidden-power",
      "tm": true,
      "level": null
    },
    {
      "name": "rain-dance",
      "tm": true,
      "level": null
    },
    {
      "name": "sunny-day",
      "tm": true,
      "level": null
    },
    {
      "name": "psych-up",
      "level": 45,
      "tm": false
    },
    {
      "name": "shadow-ball",
      "tm": true,
      "level": null
    },
    {
      "name": "facade",
      "tm": true,
      "level": null
    },
    {
      "name": "helping-hand",
      "level": 1,
      "tm": false
    },
    {
      "name": "magic-coat",
      "level": 0,
      "tm": false
    },
    {
      "name": "skill-swap",
      "level": 25,
      "tm": false
    },
    {
      "name": "secret-power",
      "tm": true,
      "level": null
    },
    {
      "name": "hyper-voice",
      "level": 0,
      "tm": false
    },
    {
      "name": "covet",
      "level": 0,
      "tm": false
    },
    {
      "name": "calm-mind",
      "tm": true,
      "level": null
    },
    {
      "name": "last-resort",
      "level": 41,
      "tm": false
    },
    {
      "name": "giga-impact",
      "tm": true,
      "level": null
    },
    {
      "name": "psyshock",
      "tm": true,
      "level": null
    },
    {
      "name": "round",
      "tm": true,
      "level": null
    },
    {
      "name": "echoed-voice",
      "tm": true,
      "level": null
    },
    {
      "name": "retaliate",
      "tm": true,
      "level": null
    },
    {
      "name": "work-up",
      "tm": true,
      "level": null
    },
    {
      "name": "disarming-voice",
      "level": 1,
      "tm": false
    },
    {
      "name": "draining-kiss",
      "level": 20,
      "tm": false
    },
    {
      "name": "misty-terrain",
      "level": 29,
      "tm": false
    },
    {
      "name": "fairy-wind",
      "level": 9,
      "tm": false
    },
    {
      "name": "moonblast",
      "level": 37,
      "tm": false
    },
    {
      "name": "confide",
      "tm": true,
      "level": null
    },
    {
      "name": "dazzling-gleam",
      "tm": true,
      "level": null
    },
    {
      "name": "baby-doll-eyes",
      "level": 9,
      "tm": false
    }
  ],
  "name": "sylveon",
  "names": {
    "french": "Nymphali",
    "german": "Feelinara",
    "spanish": "Sylveon",
    "italian": "Sylveon",
    "english": "Sylveon",
    "japanese": "\u30cb\u30f3\u30d5\u30a3\u30a2"
  },
  "pokedex_numbers": {
    "national": {
      "id": 700,
      "url": "https://thepokeapi.com/pokedex/national"
    },
    "kalos-coastal": {
      "id": 85,
      "url": "https://thepokeapi.com/pokedex/kalos-coastal"
    },
    "original-alola": {
      "id": 131,
      "url": "https://thepokeapi.com/pokedex/original-alola"
    },
    "original-akala": {
      "id": 58,
      "url": "https://thepokeapi.com/pokedex/original-akala"
    },
    "updated-alola": {
      "id": 161,
      "url": "https://thepokeapi.com/pokedex/updated-alola"
    },
    "updated-akala": {
      "id": 62,
      "url": "https://thepokeapi.com/pokedex/updated-akala"
    },
    "galar": {
      "id": 204,
      "url": "https://thepokeapi.com/pokedex/galar"
    },
    "crown-tundra": {
      "id": 82,
      "url": "https://thepokeapi.com/pokedex/crown-tundra"
    },
    "kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kanto"
    },
    "original-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-johto"
    },
    "updated-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-johto"
    },
    "kalos-central": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-central"
    },
    "isle-of-armor": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/isle-of-armor"
    },
    "updated-kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-kanto"
    },
    "conquest-gallery": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/conquest-gallery"
    },
    "original-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-melemele"
    },
    "updated-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-melemele"
    },
    "updated-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-unova"
    },
    "original-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-ulaula"
    },
    "original-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-poni"
    },
    "updated-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-ulaula"
    },
    "updated-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-poni"
    },
    "kalos-mountain": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-mountain"
    },
    "hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/hoenn"
    },
    "original-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-sinnoh"
    },
    "extended-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/extended-sinnoh"
    },
    "updated-hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-hoenn"
    },
    "original-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-unova"
    }
  },
  "region": "kalos",
  "region_id": 6,
  "shape": "quadruped",
  "species": "Intertwining Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/700.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/700.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 95
    },
    {
      "name": "attack",
      "base_stat": 65
    },
    {
      "name": "defense",
      "base_stat": 65
    },
    {
      "name": "special-attack",
      "base_stat": 110
    },
    {
      "name": "special-defense",
      "base_stat": 130
    },
    {
      "name": "speed",
      "base_stat": 60
    }
  ],
  "types": [
    {
      "name": "fairy",
      "url": "https://thepokeapi.com/type/fairy"
    }
  ],
  "weight_kilograms": 24,
  "weight_pounds": 52
}

=== hostedposted/PokemonData/data/api/pokemon/339/index.json
{
  "abilities": [
    {
      "name": "oblivious",
      "url": "https://thepokeapi.com/ability/oblivious",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "anticipation",
      "url": "https://thepokeapi.com/ability/anticipation",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "hydration",
      "url": "https://thepokeapi.com/ability/hydration",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "capture_rate": 190,
  "color": "gray",
  "damage_multipliers": {
    "normal": 1,
    "fire": 0,
    "water": 1,
    "electric": 0,
    "grass": 4,
    "ice": 1,
    "fighting": 1,
    "poison": 0,
    "ground": 1,
    "flying": 1,
    "psychic": 1,
    "bug": 1,
    "rock": 0,
    "ghost": 1,
    "dragon": 1,
    "dark": 1,
    "steel": 0,
    "fairy": 1
  },
  "description": "Its whiskers are filled with nerves. They can sense smells and flavors just as a person\u2019s nose or tongue would.",
  "egg_groups": [
    "water2"
  ],
  "evolution_chain": [
    [
      "barboach"
    ],
    [
      "whiscash"
    ]
  ],
  "evolves_from_species": null,
  "growth_rate": "medium",
  "height": 16,
  "id": 339,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "headbutt",
      "level": 0,
      "tm": false
    },
    {
      "name": "take-down",
      "tm": false,
      "level": null
    },
    {
      "name": "thrash",
      "tm": false,
      "level": null
    },
    {
      "name": "double-edge",
      "level": 0,
      "tm": false
    },
    {
      "name": "water-gun",
      "level": 11,
      "tm": false
    },
    {
      "name": "hydro-pump",
      "tm": false,
      "level": null
    },
    {
      "name": "surf",
      "tm": true,
      "level": null
    },
    {
      "name": "ice-beam",
      "tm": true,
      "level": null
    },
    {
      "name": "blizzard",
      "tm": true,
      "level": null
    },
    {
      "name": "earthquake",
      "level": 31,
      "tm": false
    },
    {
      "name": "fissure",
      "level": 41,
      "tm": false
    },
    {
      "name": "toxic",
      "tm": true,
      "level": null
    },
    {
      "name": "mimic",
      "level": 0,
      "tm": false
    },
    {
      "name": "double-team",
      "tm": true,
      "level": null
    },
    {
      "name": "waterfall",
      "tm": true,
      "level": null
    },
    {
      "name": "amnesia",
      "level": 21,
      "tm": false
    },
    {
      "name": "rest",
      "level": 26,
      "tm": false
    },
    {
      "name": "substitute",
      "level": 0,
      "tm": false
    },
    {
      "name": "snore",
      "level": 26,
      "tm": false
    },
    {
      "name": "flail",
      "tm": false,
      "level": null
    },
    {
      "name": "protect",
      "tm": true,
      "level": null
    },
    {
      "name": "mud-slap",
      "level": 1,
      "tm": false
    },
    {
      "name": "icy-wind",
      "level": 0,
      "tm": false
    },
    {
      "name": "sandstorm",
      "tm": true,
      "level": null
    },
    {
      "name": "endure",
      "level": 0,
      "tm": false
    },
    {
      "name": "swagger",
      "level": 0,
      "tm": false
    },
    {
      "name": "spark",
      "tm": false,
      "level": null
    },
    {
      "name": "attract",
      "tm": true,
      "level": null
    },
    {
      "name": "sleep-talk",
      "level": 0,
      "tm": false
    },
    {
      "name": "return",
      "tm": true,
      "level": null
    },
    {
      "name": "frustration",
      "tm": true,
      "level": null
    },
    {
      "name": "magnitude",
      "level": 16,
      "tm": false
    },
    {
      "name": "hidden-power",
      "tm": true,
      "level": null
    },
    {
      "name": "rain-dance",
      "tm": true,
      "level": null
    },
    {
      "name": "future-sight",
      "level": 36,
      "tm": false
    },
    {
      "name": "whirlpool",
      "tm": false,
      "level": null
    },
    {
      "name": "hail",
      "tm": true,
      "level": null
    },
    {
      "name": "facade",
      "tm": true,
      "level": null
    },
    {
      "name": "secret-power",
      "tm": true,
      "level": null
    },
    {
      "name": "dive",
      "tm": true,
      "level": null
    },
    {
      "name": "mud-sport",
      "level": 6,
      "tm": false
    },
    {
      "name": "rock-tomb",
      "tm": true,
      "level": null
    },
    {
      "name": "muddy-water",
      "tm": false,
      "level": null
    },
    {
      "name": "bounce",
      "level": 0,
      "tm": false
    },
    {
      "name": "mud-shot",
      "tm": false,
      "level": null
    },
    {
      "name": "water-sport",
      "level": 6,
      "tm": false
    },
    {
      "name": "dragon-dance",
      "tm": false,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "natural-gift",
      "tm": true,
      "level": null
    },
    {
      "name": "aqua-tail",
      "level": 35,
      "tm": false
    },
    {
      "name": "earth-power",
      "level": 0,
      "tm": false
    },
    {
      "name": "mud-bomb",
      "level": 14,
      "tm": false
    },
    {
      "name": "captivate",
      "tm": true,
      "level": null
    },
    {
      "name": "round",
      "tm": true,
      "level": null
    },
    {
      "name": "scald",
      "tm": true,
      "level": null
    },
    {
      "name": "bulldoze",
      "tm": true,
      "level": null
    },
    {
      "name": "confide",
      "tm": true,
      "level": null
    }
  ],
  "name": "barboach",
  "names": {
    "french": "Barloche",
    "german": "Schmerbe",
    "spanish": "Barboach",
    "italian": "Barboach",
    "english": "Barboach",
    "japanese": "\u30c9\u30b8\u30e7\u30c3\u30c1"
  },
  "pokedex_numbers": {
    "national": {
      "id": 339,
      "url": "https://thepokeapi.com/pokedex/national"
    },
    "hoenn": {
      "id": 127,
      "url": "https://thepokeapi.com/pokedex/hoenn"
    },
    "original-sinnoh": {
      "id": 80,
      "url": "https://thepokeapi.com/pokedex/original-sinnoh"
    },
    "extended-sinnoh": {
      "id": 80,
      "url": "https://thepokeapi.com/pokedex/extended-sinnoh"
    },
    "kalos-mountain": {
      "id": 40,
      "url": "https://thepokeapi.com/pokedex/kalos-mountain"
    },
    "updated-hoenn": {
      "id": 132,
      "url": "https://thepokeapi.com/pokedex/updated-hoenn"
    },
    "original-alola": {
      "id": 93,
      "url": "https://thepokeapi.com/pokedex/original-alola"
    },
    "original-melemele": {
      "id": 93,
      "url": "https://thepokeapi.com/pokedex/original-melemele"
    },
    "original-akala": {
      "id": 36,
      "url": "https://thepokeapi.com/pokedex/original-akala"
    },
    "original-poni": {
      "id": 43,
      "url": "https://thepokeapi.com/pokedex/original-poni"
    },
    "updated-alola": {
      "id": 113,
      "url": "https://thepokeapi.com/pokedex/updated-alola"
    },
    "updated-melemele": {
      "id": 113,
      "url": "https://thepokeapi.com/pokedex/updated-melemele"
    },
    "updated-akala": {
      "id": 36,
      "url": "https://thepokeapi.com/pokedex/updated-akala"
    },
    "updated-poni": {
      "id": 55,
      "url": "https://thepokeapi.com/pokedex/updated-poni"
    },
    "galar": {
      "id": 228,
      "url": "https://thepokeapi.com/pokedex/galar"
    },
    "isle-of-armor": {
      "id": 137,
      "url": "https://thepokeapi.com/pokedex/isle-of-armor"
    },
    "crown-tundra": {
      "id": 60,
      "url": "https://thepokeapi.com/pokedex/crown-tundra"
    },
    "kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kanto"
    },
    "original-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-johto"
    },
    "updated-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-johto"
    },
    "kalos-central": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-central"
    },
    "updated-kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-kanto"
    },
    "conquest-gallery": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/conquest-gallery"
    },
    "updated-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-unova"
    },
    "original-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-ulaula"
    },
    "updated-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-ulaula"
    },
    "kalos-coastal": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-coastal"
    },
    "original-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-unova"
    }
  },
  "region": "hoenn",
  "region_id": 3,
  "shape": "fish",
  "species": "Whiskers Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/339.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/339.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 50
    },
    {
      "name": "attack",
      "base_stat": 48
    },
    {
      "name": "defense",
      "base_stat": 43
    },
    {
      "name": "special-attack",
      "base_stat": 46
    },
    {
      "name": "special-defense",
      "base_stat": 41
    },
    {
      "name": "speed",
      "base_stat": 60
    }
  ],
  "types": [
    {
      "name": "water",
      "url": "https://thepokeapi.com/type/water"
    },
    {
      "name": "ground",
      "url": "https://thepokeapi.com/type/ground"
    }
  ],
  "weight_kilograms": 2,
  "weight_pounds": 4
}
