=== hostedposted/PokemonData/data/schema/pokemon/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "abilities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "capture_rate": {
      "type": "integer"
    },
    "color": {
      "type": "string"
    },
    "damage_multipliers": {
      "type": "object",
      "properties": {
        "normal": {
          "type": "integer"
        },
        "fire": {
          "type": "integer"
        },
        "water": {
          "type": "integer"
        },
        "electric": {
          "type": "integer"
        },
        "grass": {
          "type": "integer"
        },
        "ice": {
          "type": "integer"
        },
        "fighting": {
          "type": "integer"
        },
        "poison": {
          "type": "integer"
        },
        "ground": {
          "type": "integer"
        },
        "flying": {
          "type": "integer"
        },
        "psychic": {
          "type": "integer"
        },
        "bug": {
          "type": "integer"
        },
        "rock": {
          "type": "integer"
        },
        "ghost": {
          "type": "integer"
        },
        "dragon": {
          "type": "integer"
        },
        "dark": {
          "type": "integer"
        },
        "steel": {
          "type": "integer"
        },
        "fairy": {
          "type": "integer"
        }
      },
      "required": [
        "bug",
        "dark",
        "dragon",
        "electric",
        "fairy",
        "fighting",
        "fire",
        "flying",
        "ghost",
        "grass",
        "ground",
        "ice",
        "normal",
        "poison",
        "psychic",
        "rock",
        "steel",
        "water"
      ]
    },
    "description": {
      "type": [
        "null",
        "string"
      ]
    },
    "egg_groups": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "evolution_chain": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "evolves_from_species": {
      "type": [
        "null",
        "string"
      ]
    },
    "growth_rate": {
      "type": "string"
    },
    "height": {
      "type": "integer"
    },
    "id": {
      "type": "integer"
    },
    "is_baby": {
      "type": "boolean"
    },
    "is_legendary": {
      "type": "boolean"
    },
    "is_mythical": {
      "type": "boolean"
    },
    "moves": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "tm": {
            "type": "boolean"
          },
          "level": {
            "type": [
              "integer",
              "null"
            ]
          }
        },
        "required": [
          "level",
          "name",
          "tm"
        ]
      }
    },
    "name": {
      "type": "string"
    },
    "names": {
      "type": "object",
      "properties": {
        "french": {
          "type": "string"
        },
        "german": {
          "type": "string"
        },
        "spanish": {
          "type": "string"
        },
        "italian": {
          "type": "string"
        },
        "english": {
          "type": "string"
        },
        "japanese": {
          "type": "string"
        }
      },
      "required": [
        "english",
        "french",
        "german",
        "italian",
        "japanese",
        "spanish"
      ]
    },
    "pokedex_numbers": {
      "type": "object",
      "properties": {
        "national": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-johto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-central": {
          "type": [
            "integer",
            "null"
          ]
        },
        "isle-of-armor": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-kanto": {
          "type": [
            "integer",
            "null"
          ]
        },
        "conquest-gallery": {
          "type": [
            "integer",
            "null"
          ]
        },
        "galar": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-alola": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-melemele": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-akala": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-unova": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-ulaula": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-poni": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-mountain": {
          "type": [
            "integer",
            "null"
          ]
        },
        "hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "extended-sinnoh": {
          "type": [
            "integer",
            "null"
          ]
        },
        "updated-hoenn": {
          "type": [
            "integer",
            "null"
          ]
        },
        "kalos-coastal": {
          "type": [
            "integer",
            "null"
          ]
        },
        "crown-tundra": {
          "type": [
            "integer",
            "null"
          ]
        },
        "original-unova": {
          "type": [
            "integer",
            "null"
          ]
        }
      }
    },
    "region": {
      "type": "string"
    },
    "region_id": {
      "type": "integer"
    },
    "shape": {
      "type": "string"
    },
    "species": {
      "type": "string"
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "shiny": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "shiny"
      ]
    },
    "stats": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "base_stat": {
            "type": "integer"
          }
        },
        "required": [
          "base_stat",
          "name"
        ]
      }
    },
    "types": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "url"
        ]
      }
    },
    "weight_kilograms": {
      "type": "integer"
    },
    "weight_pounds": {
      "type": "integer"
    }
  }
}

=== hostedposted/PokemonData/data/api/pokemon/873/index.json
{
  "abilities": [
    {
      "name": "shield-dust",
      "url": "https://thepokeapi.com/ability/shield-dust",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "ice-scales",
      "url": "https://thepokeapi.com/ability/ice-scales",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "capture_rate": 75,
  "color": "white",
  "damage_multipliers": {
    "normal": 1,
    "fire": 4,
    "water": 1,
    "electric": 1,
    "grass": 0,
    "ice": 0,
    "fighting": 1,
    "poison": 1,
    "ground": 0,
    "flying": 2,
    "psychic": 1,
    "bug": 1,
    "rock": 4,
    "ghost": 1,
    "dragon": 1,
    "dark": 1,
    "steel": 2,
    "fairy": 1
  },
  "description": "It shows no mercy to any who desecrate fields and mountains. It will fly around on its icy wings, causing a blizzard to chase offenders away.",
  "egg_groups": [],
  "evolution_chain": [
    [
      "snom"
    ],
    [
      "frosmoth"
    ]
  ],
  "evolves_from_species": "snom",
  "growth_rate": "medium",
  "height": 51,
  "id": 873,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "icy wind",
      "level": 0,
      "tm": false
    },
    {
      "name": "icy wind",
      "level": 1,
      "tm": false
    },
    {
      "name": "powder snow",
      "level": 1,
      "tm": false
    },
    {
      "name": "struggle bug",
      "level": 1,
      "tm": false
    },
    {
      "name": "helping hand",
      "level": 1,
      "tm": false
    },
    {
      "name": "attract",
      "level": 1,
      "tm": false
    },
    {
      "name": "stun spore",
      "level": 4,
      "tm": false
    },
    {
      "name": "infestation",
      "level": 8,
      "tm": false
    },
    {
      "name": "mist",
      "level": 12,
      "tm": false
    },
    {
      "name": "defog",
      "level": 16,
      "tm": false
    },
    {
      "name": "feather dance",
      "level": 21,
      "tm": false
    },
    {
      "name": "aurora beam",
      "level": 24,
      "tm": false
    },
    {
      "name": "hail",
      "level": 28,
      "tm": false
    },
    {
      "name": "bug buzz",
      "level": 32,
      "tm": false
    },
    {
      "name": "aurora veil",
      "level": 36,
      "tm": false
    },
    {
      "name": "blizzard",
      "level": 40,
      "tm": false
    },
    {
      "name": "tailwind",
      "level": 44,
      "tm": false
    },
    {
      "name": "wide guard",
      "level": 48,
      "tm": false
    },
    {
      "name": "quiver dance",
      "level": 52,
      "tm": false
    },
    {
      "name": "focus-punch",
      "tm": true,
      "level": null
    },
    {
      "name": "focus-punch",
      "tm": true,
      "level": null
    },
    {
      "name": "work-up",
      "tm": true,
      "level": null
    },
    {
      "name": "work-up",
      "tm": true,
      "level": null
    },
    {
      "name": "razor-wind",
      "tm": true,
      "level": null
    },
    {
      "name": "headbutt",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "dragon-claw",
      "tm": true,
      "level": null
    },
    {
      "name": "curse",
      "tm": true,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "water-pulse",
      "tm": true,
      "level": null
    },
    {
      "name": "psyshock",
      "tm": true,
      "level": null
    },
    {
      "name": "whirlwind",
      "tm": true,
      "level": null
    },
    {
      "name": "calm-mind",
      "tm": true,
      "level": null
    },
    {
      "name": "roar",
      "tm": true,
      "level": null
    },
    {
      "name": "roar",
      "tm": true,
      "level": null
    },
    {
      "name": "toxic",
      "tm": true,
      "level": null
    }
  ],
  "name": "frosmoth",
  "names": {
    "french": "Beldeneige",
    "german": "Mottineva",
    "spanish": "Frosmoth",
    "italian": "Frosmoth",
    "english": "Frosmoth",
    "japanese": "\u30e2\u30b9\u30ce\u30a6"
  },
  "pokedex_numbers": {
    "national": 873,
    "galar": 350,
    "crown-tundra": 2,
    "kanto": null,
    "original-johto": null,
    "updated-johto": null,
    "kalos-central": null,
    "isle-of-armor": null,
    "updated-kanto": null,
    "conquest-gallery": null,
    "original-alola": null,
    "original-melemele": null,
    "original-akala": null,
    "updated-alola": null,
    "updated-melemele": null,
    "updated-akala": null,
    "updated-unova": null,
    "original-ulaula": null,
    "original-poni": null,
    "updated-ulaula": null,
    "updated-poni": null,
    "kalos-mountain": null,
    "hoenn": null,
    "original-sinnoh": null,
    "extended-sinnoh": null,
    "updated-hoenn": null,
    "kalos-coastal": null,
    "original-unova": null
  },
  "region": "galar",
  "region_id": 8,
  "shape": "bug-wings",
  "species": "Frost Moth Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/873.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/873.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 70
    },
    {
      "name": "attack",
      "base_stat": 65
    },
    {
      "name": "defense",
      "base_stat": 60
    },
    {
      "name": "special-attack",
      "base_stat": 125
    },
    {
      "name": "special-defense",
      "base_stat": 90
    },
    {
      "name": "speed",
      "base_stat": 65
    }
  ],
  "types": [
    {
      "name": "ice",
      "url": "https://thepokeapi.com/type/ice"
    },
    {
      "name": "bug",
      "url": "https://thepokeapi.com/type/bug"
    }
  ],
  "weight_kilograms": 42,
  "weight_pounds": 93
}

=== hostedposted/PokemonData/data/api/pokemon/672/index.json
{
  "abilities": [
    {
      "name": "sap-sipper",
      "url": "https://thepokeapi.com/ability/sap-sipper",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "grass-pelt",
      "url": "https://thepokeapi.com/ability/grass-pelt",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "capture_rate": 200,
  "color": "brown",
  "damage_multipliers": {
    "normal": 1,
    "fire": 2,
    "water": 0,
    "electric": 0,
    "grass": 0,
    "ice": 2,
    "fighting": 2,
    "poison": 2,
    "ground": 0,
    "flying": 2,
    "psychic": 1,
    "bug": 2,
    "rock": 1,
    "ghost": 0,
    "dragon": 1,
    "dark": 1,
    "steel": 1,
    "fairy": 1
  },
  "description": "If it has sunshine and water, it doesn\u2019t need to eat, because it can generate energy from the leaves on its back.",
  "egg_groups": [
    "ground"
  ],
  "evolution_chain": [
    [
      "skiddo"
    ],
    [
      "gogoat"
    ]
  ],
  "evolves_from_species": null,
  "growth_rate": "medium",
  "height": 35,
  "id": 672,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "moves": [
    {
      "name": "vine-whip",
      "level": 7,
      "tm": false
    },
    {
      "name": "tackle",
      "level": 1,
      "tm": false
    },
    {
      "name": "take-down",
      "level": 22,
      "tm": false
    },
    {
      "name": "double-edge",
      "level": 38,
      "tm": false
    },
    {
      "name": "tail-whip",
      "level": 9,
      "tm": false
    },
    {
      "name": "roar",
      "tm": true,
      "level": null
    },
    {
      "name": "surf",
      "tm": true,
      "level": null
    },
    {
      "name": "strength",
      "tm": true,
      "level": null
    },
    {
      "name": "leech-seed",
      "level": 12,
      "tm": false
    },
    {
      "name": "growth",
      "level": 1,
      "tm": false
    },
    {
      "name": "razor-leaf",
      "level": 13,
      "tm": false
    },
    {
      "name": "solar-beam",
      "tm": true,
      "level": null
    },
    {
      "name": "dig",
      "tm": true,
      "level": null
    },
    {
      "name": "toxic",
      "tm": true,
      "level": null
    },
    {
      "name": "double-team",
      "tm": true,
      "level": null
    },
    {
      "name": "defense-curl",
      "tm": false,
      "level": null
    },
    {
      "name": "rest",
      "tm": true,
      "level": null
    },
    {
      "name": "rock-slide",
      "tm": true,
      "level": null
    },
    {
      "name": "substitute",
      "tm": true,
      "level": null
    },
    {
      "name": "snore",
      "level": 0,
      "tm": false
    },
    {
      "name": "protect",
      "tm": true,
      "level": null
    },
    {
      "name": "giga-drain",
      "level": 0,
      "tm": false
    },
    {
      "name": "rollout",
      "tm": false,
      "level": null
    },
    {
      "name": "swagger",
      "tm": true,
      "level": null
    },
    {
      "name": "milk-drink",
      "level": 50,
      "tm": false
    },
    {
      "name": "attract",
      "tm": true,
      "level": null
    },
    {
      "name": "sleep-talk",
      "tm": true,
      "level": null
    },
    {
      "name": "return",
      "tm": true,
      "level": null
    },
    {
      "name": "frustration",
      "tm": true,
      "level": null
    },
    {
      "name": "iron-tail",
      "level": 0,
      "tm": false
    },
    {
      "name": "synthesis",
      "level": 20,
      "tm": false
    },
    {
      "name": "hidden-power",
      "tm": true,
      "level": null
    },
    {
      "name": "rain-dance",
      "tm": true,
      "level": null
    },
    {
      "name": "sunny-day",
      "tm": true,
      "level": null
    },
    {
      "name": "rock-smash",
      "tm": true,
      "level": null
    },
    {
      "name": "facade",
      "tm": true,
      "level": null
    },
    {
      "name": "nature-power",
      "tm": true,
      "level": null
    },
    {
      "name": "brick-break",
      "tm": true,
      "level": null
    },
    {
      "name": "secret-power",
      "tm": true,
      "level": null
    },
    {
      "name": "bulk-up",
      "level": 34,
      "tm": false
    },
    {
      "name": "leaf-blade",
      "level": 45,
      "tm": false
    },
    {
      "name": "payback",
      "tm": true,
      "level": null
    },
    {
      "name": "worry-seed",
      "level": 16,
      "tm": false
    },
    {
      "name": "seed-bomb",
      "level": 30,
      "tm": false
    },
    {
      "name": "energy-ball",
      "tm": true,
      "level": null
    },
    {
      "name": "zen-headbutt",
      "level": 0,
      "tm": false
    },
    {
      "name": "grass-knot",
      "tm": true,
      "level": null
    },
    {
      "name": "round",
      "tm": true,
      "level": null
    },
    {
      "name": "retaliate",
      "tm": true,
      "level": null
    },
    {
      "name": "bulldoze",
      "level": 26,
      "tm": false
    },
    {
      "name": "work-up",
      "tm": true,
      "level": null
    },
    {
      "name": "wild-charge",
      "tm": true,
      "level": null
    },
    {
      "name": "horn-leech",
      "level": 42,
      "tm": false
    },
    {
      "name": "grassy-terrain",
      "tm": false,
      "level": null
    },
    {
      "name": "confide",
      "tm": true,
      "level": null
    }
  ],
  "name": "skiddo",
  "names": {
    "french": "Cabriolaine",
    "german": "M\u00e4hikel",
    "spanish": "Skiddo",
    "italian": "Skiddo",
    "english": "Skiddo",
    "japanese": "\u30e1\u30a7\u30fc\u30af\u30eb"
  },
  "pokedex_numbers": {
    "national": {
      "id": 672,
      "url": "https://thepokeapi.com/pokedex/national"
    },
    "kalos-central": {
      "id": 89,
      "url": "https://thepokeapi.com/pokedex/kalos-central"
    },
    "kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kanto"
    },
    "original-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-johto"
    },
    "updated-johto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-johto"
    },
    "isle-of-armor": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/isle-of-armor"
    },
    "updated-kanto": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-kanto"
    },
    "conquest-gallery": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/conquest-gallery"
    },
    "galar": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/galar"
    },
    "original-alola": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-alola"
    },
    "original-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-melemele"
    },
    "original-akala": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-akala"
    },
    "updated-alola": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-alola"
    },
    "updated-melemele": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-melemele"
    },
    "updated-akala": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-akala"
    },
    "updated-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-unova"
    },
    "original-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-ulaula"
    },
    "original-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-poni"
    },
    "updated-ulaula": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-ulaula"
    },
    "updated-poni": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-poni"
    },
    "kalos-mountain": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-mountain"
    },
    "hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/hoenn"
    },
    "original-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-sinnoh"
    },
    "extended-sinnoh": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/extended-sinnoh"
    },
    "updated-hoenn": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/updated-hoenn"
    },
    "kalos-coastal": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/kalos-coastal"
    },
    "crown-tundra": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/crown-tundra"
    },
    "original-unova": {
      "id": null,
      "url": "https://thepokeapi.com/pokedex/original-unova"
    }
  },
  "region": "kalos",
  "region_id": 6,
  "shape": "quadruped",
  "species": "Mount Pok\u00e9mon",
  "sprites": {
    "default": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/672.png",
    "shiny": "https://raw.githubusercontent.com/hostedposted/PokemonData/master/sprites/pokemon/shiny/672.png"
  },
  "stats": [
    {
      "name": "hp",
      "base_stat": 66
    },
    {
      "name": "attack",
      "base_stat": 65
    },
    {
      "name": "defense",
      "base_stat": 48
    },
    {
      "name": "special-attack",
      "base_stat": 62
    },
    {
      "name": "special-defense",
      "base_stat": 57
    },
    {
      "name": "speed",
      "base_stat": 52
    }
  ],
  "types": [
    {
      "name": "grass",
      "url": "https://thepokeapi.com/type/grass"
    }
  ],
  "weight_kilograms": 31,
  "weight_pounds": 68
}
