=== hostedposted/PokemonData/data/schema/pokedex/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "is_main_series": {
      "type": "boolean"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "type": [
        "null",
        "string"
      ]
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "url"
        ]
      }
    }
  },
  "required": [
    "region"
  ]
}

=== hostedposted/PokemonData/data/api/pokedex/original-akala/index.json
{
  "description": "Sun/Moon Akala dex",
  "id": 18,
  "is_main_series": true,
  "name": "original-akala",
  "region": "alola",
  "pokemon": [
    {
      "id": 1,
      "name": "pikipek",
      "url": "https://thepokeapi.com/pokemon/pikipek"
    },
    {
      "id": 2,
      "name": "trumbeak",
      "url": "https://thepokeapi.com/pokemon/trumbeak"
    },
    {
      "id": 3,
      "name": "toucannon",
      "url": "https://thepokeapi.com/pokemon/toucannon"
    },
    {
      "id": 4,
      "name": "yungoos",
      "url": "https://thepokeapi.com/pokemon/yungoos"
    },
    {
      "id": 5,
      "name": "gumshoos",
      "url": "https://thepokeapi.com/pokemon/gumshoos"
    },
    {
      "id": 6,
      "name": "rattata",
      "url": "https://thepokeapi.com/pokemon/rattata"
    },
    {
      "id": 7,
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate"
    },
    {
      "id": 8,
      "name": "caterpie",
      "url": "https://thepokeapi.com/pokemon/caterpie"
    },
    {
      "id": 9,
      "name": "metapod",
      "url": "https://thepokeapi.com/pokemon/metapod"
    },
    {
      "id": 10,
      "name": "butterfree",
      "url": "https://thepokeapi.com/pokemon/butterfree"
    },
    {
      "id": 11,
      "name": "grubbin",
      "url": "https://thepokeapi.com/pokemon/grubbin"
    },
    {
      "id": 12,
      "name": "charjabug",
      "url": "https://thepokeapi.com/pokemon/charjabug"
    },
    {
      "id": 13,
      "name": "vikavolt",
      "url": "https://thepokeapi.com/pokemon/vikavolt"
    },
    {
      "id": 14,
      "name": "bonsly",
      "url": "https://thepokeapi.com/pokemon/bonsly"
    },
    {
      "id": 15,
      "name": "sudowoodo",
      "url": "https://thepokeapi.com/pokemon/sudowoodo"
    },
    {
      "id": 16,
      "name": "happiny",
      "url": "https://thepokeapi.com/pokemon/happiny"
    },
    {
      "id": 17,
      "name": "chansey",
      "url": "https://thepokeapi.com/pokemon/chansey"
    },
    {
      "id": 18,
      "name": "blissey",
      "url": "https://thepokeapi.com/pokemon/blissey"
    },
    {
      "id": 19,
      "name": "wingull",
      "url": "https://thepokeapi.com/pokemon/wingull"
    },
    {
      "id": 20,
      "name": "pelipper",
      "url": "https://thepokeapi.com/pokemon/pelipper"
    },
    {
      "id": 21,
      "name": "crabrawler",
      "url": "https://thepokeapi.com/pokemon/crabrawler"
    },
    {
      "id": 22,
      "name": "crabominable",
      "url": "https://thepokeapi.com/pokemon/crabominable"
    },
    {
      "id": 23,
      "name": "gastly",
      "url": "https://thepokeapi.com/pokemon/gastly"
    },
    {
      "id": 24,
      "name": "haunter",
      "url": "https://thepokeapi.com/pokemon/haunter"
    },
    {
      "id": 25,
      "name": "gengar",
      "url": "https://thepokeapi.com/pokemon/gengar"
    },
    {
      "id": 26,
      "name": "zubat",
      "url": "https://thepokeapi.com/pokemon/zubat"
    },
    {
      "id": 27,
      "name": "golbat",
      "url": "https://thepokeapi.com/pokemon/golbat"
    },
    {
      "id": 28,
      "name": "crobat",
      "url": "https://thepokeapi.com/pokemon/crobat"
    },
    {
      "id": 29,
      "name": "diglett",
      "url": "https://thepokeapi.com/pokemon/diglett"
    },
    {
      "id": 30,
      "name": "dugtrio",
      "url": "https://thepokeapi.com/pokemon/dugtrio"
    },
    {
      "id": 31,
      "name": "oricorio",
      "url": "https://thepokeapi.com/pokemon/oricorio"
    },
    {
      "id": 32,
      "name": "psyduck",
      "url": "https://thepokeapi.com/pokemon/psyduck"
    },
    {
      "id": 33,
      "name": "golduck",
      "url": "https://thepokeapi.com/pokemon/golduck"
    },
    {
      "id": 34,
      "name": "magikarp",
      "url": "https://thepokeapi.com/pokemon/magikarp"
    },
    {
      "id": 35,
      "name": "gyarados",
      "url": "https://thepokeapi.com/pokemon/gyarados"
    },
    {
      "id": 36,
      "name": "barboach",
      "url": "https://thepokeapi.com/pokemon/barboach"
    },
    {
      "id": 37,
      "name": "whiscash",
      "url": "https://thepokeapi.com/pokemon/whiscash"
    },
    {
      "id": 38,
      "name": "tentacool",
      "url": "https://thepokeapi.com/pokemon/tentacool"
    },
    {
      "id": 39,
      "name": "tentacruel",
      "url": "https://thepokeapi.com/pokemon/tentacruel"
    },
    {
      "id": 40,
      "name": "finneon",
      "url": "https://thepokeapi.com/pokemon/finneon"
    },
    {
      "id": 41,
      "name": "lumineon",
      "url": "https://thepokeapi.com/pokemon/lumineon"
    },
    {
      "id": 42,
      "name": "wishiwashi",
      "url": "https://thepokeapi.com/pokemon/wishiwashi"
    },
    {
      "id": 43,
      "name": "luvdisc",
      "url": "https://thepokeapi.com/pokemon/luvdisc"
    },
    {
      "id": 44,
      "name": "corsola",
      "url": "https://thepokeapi.com/pokemon/corsola"
    },
    {
      "id": 45,
      "name": "mareanie",
      "url": "https://thepokeapi.com/pokemon/mareanie"
    },
    {
      "id": 46,
      "name": "toxapex",
      "url": "https://thepokeapi.com/pokemon/toxapex"
    },
    {
      "id": 47,
      "name": "lillipup",
      "url": "https://thepokeapi.com/pokemon/lillipup"
    },
    {
      "id": 48,
      "name": "herdier",
      "url": "https://thepokeapi.com/pokemon/herdier"
    },
    {
      "id": 49,
      "name": "stoutland",
      "url": "https://thepokeapi.com/pokemon/stoutland"
    },
    {
      "id": 50,
      "name": "eevee",
      "url": "https://thepokeapi.com/pokemon/eevee"
    },
    {
      "id": 51,
      "name": "vaporeon",
      "url": "https://thepokeapi.com/pokemon/vaporeon"
    },
    {
      "id": 52,
      "name": "jolteon",
      "url": "https://thepokeapi.com/pokemon/jolteon"
    },
    {
      "id": 53,
      "name": "flareon",
      "url": "https://thepokeapi.com/pokemon/flareon"
    },
    {
      "id": 54,
      "name": "espeon",
      "url": "https://thepokeapi.com/pokemon/espeon"
    },
    {
      "id": 55,
      "name": "umbreon",
      "url": "https://thepokeapi.com/pokemon/umbreon"
    },
    {
      "id": 56,
      "name": "leafeon",
      "url": "https://thepokeapi.com/pokemon/leafeon"
    },
    {
      "id": 57,
      "name": "glaceon",
      "url": "https://thepokeapi.com/pokemon/glaceon"
    },
    {
      "id": 58,
      "name": "sylveon",
      "url": "https://thepokeapi.com/pokemon/sylveon"
    },
    {
      "id": 59,
      "name": "mudbray",
      "url": "https://thepokeapi.com/pokemon/mudbray"
    },
    {
      "id": 60,
      "name": "mudsdale",
      "url": "https://thepokeapi.com/pokemon/mudsdale"
    },
    {
      "id": 61,
      "name": "igglybuff",
      "url": "https://thepokeapi.com/pokemon/igglybuff"
    },
    {
      "id": 62,
      "name": "jigglypuff",
      "url": "https://thepokeapi.com/pokemon/jigglypuff"
    },
    {
      "id": 63,
      "name": "wigglytuff",
      "url": "https://thepokeapi.com/pokemon/wigglytuff"
    },
    {
      "id": 64,
      "name": "tauros",
      "url": "https://thepokeapi.com/pokemon/tauros"
    },
    {
      "id": 65,
      "name": "miltank",
      "url": "https://thepokeapi.com/pokemon/miltank"
    },
    {
      "id": 66,
      "name": "surskit",
      "url": "https://thepokeapi.com/pokemon/surskit"
    },
    {
      "id": 67,
      "name": "masquerain",
      "url": "https://thepokeapi.com/pokemon/masquerain"
    },
    {
      "id": 68,
      "name": "dewpider",
      "url": "https://thepokeapi.com/pokemon/dewpider"
    },
    {
      "id": 69,
      "name": "araquanid",
      "url": "https://thepokeapi.com/pokemon/araquanid"
    },
    {
      "id": 70,
      "name": "fomantis",
      "url": "https://thepokeapi.com/pokemon/fomantis"
    },
    {
      "id": 71,
      "name": "lurantis",
      "url": "https://thepokeapi.com/pokemon/lurantis"
    },
    {
      "id": 72,
      "name": "morelull",
      "url": "https://thepokeapi.com/pokemon/morelull"
    },
    {
      "id": 73,
      "name": "shiinotic",
      "url": "https://thepokeapi.com/pokemon/shiinotic"
    },
    {
      "id": 74,
      "name": "paras",
      "url": "https://thepokeapi.com/pokemon/paras"
    },
    {
      "id": 75,
      "name": "parasect",
      "url": "https://thepokeapi.com/pokemon/parasect"
    },
    {
      "id": 76,
      "name": "poliwag",
      "url": "https://thepokeapi.com/pokemon/poliwag"
    },
    {
      "id": 77,
      "name": "poliwhirl",
      "url": "https://thepokeapi.com/pokemon/poliwhirl"
    },
    {
      "id": 78,
      "name": "poliwrath",
      "url": "https://thepokeapi.com/pokemon/poliwrath"
    },
    {
      "id": 79,
      "name": "politoed",
      "url": "https://thepokeapi.com/pokemon/politoed"
    },
    {
      "id": 80,
      "name": "goldeen",
      "url": "https://thepokeapi.com/pokemon/goldeen"
    },
    {
      "id": 81,
      "name": "seaking",
      "url": "https://thepokeapi.com/pokemon/seaking"
    },
    {
      "id": 82,
      "name": "feebas",
      "url": "https://thepokeapi.com/pokemon/feebas"
    },
    {
      "id": 83,
      "name": "milotic",
      "url": "https://thepokeapi.com/pokemon/milotic"
    },
    {
      "id": 84,
      "name": "alomomola",
      "url": "https://thepokeapi.com/pokemon/alomomola"
    },
    {
      "id": 85,
      "name": "fletchling",
      "url": "https://thepokeapi.com/pokemon/fletchling"
    },
    {
      "id": 86,
      "name": "fletchinder",
      "url": "https://thepokeapi.com/pokemon/fletchinder"
    },
    {
      "id": 87,
      "name": "talonflame",
      "url": "https://thepokeapi.com/pokemon/talonflame"
    },
    {
      "id": 88,
      "name": "salandit",
      "url": "https://thepokeapi.com/pokemon/salandit"
    },
    {
      "id": 89,
      "name": "salazzle",
      "url": "https://thepokeapi.com/pokemon/salazzle"
    },
    {
      "id": 90,
      "name": "cubone",
      "url": "https://thepokeapi.com/pokemon/cubone"
    },
    {
