=== hostedposted/PokemonData/data/schema/type/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "damage_relations": {
      "type": "object",
      "properties": {
        "double_damage_from": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "double_damage_to": {
          "type": "array"
        },
        "half_damage_from": {
          "type": "array"
        },
        "half_damage_to": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "no_damage_from": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        },
        "no_damage_to": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "url"
            ]
          }
        }
      },
      "required": [
        "double_damage_from",
        "double_damage_to",
        "half_damage_from",
        "half_damage_to",
        "no_damage_from",
        "no_damage_to"
      ]
    },
    "name": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "slot",
          "url"
        ]
      }
    }
  },
  "required": [
    "damage_relations",
    "id",
    "name",
    "pokemon"
  ]
}

=== hostedposted/PokemonData/data/api/type/rock/index.json
{
  "damage_relations": {
    "double_damage_from": [
      {
        "name": "fighting",
        "url": "https://thepokeapi.com/type/fighting"
      },
      {
        "name": "ground",
        "url": "https://thepokeapi.com/type/ground"
      },
      {
        "name": "steel",
        "url": "https://thepokeapi.com/type/steel"
      },
      {
        "name": "water",
        "url": "https://thepokeapi.com/type/water"
      },
      {
        "name": "grass",
        "url": "https://thepokeapi.com/type/grass"
      }
    ],
    "double_damage_to": [
      {
        "name": "flying",
        "url": "https://thepokeapi.com/type/flying"
      },
      {
        "name": "bug",
        "url": "https://thepokeapi.com/type/bug"
      },
      {
        "name": "fire",
        "url": "https://thepokeapi.com/type/fire"
      },
      {
        "name": "ice",
        "url": "https://thepokeapi.com/type/ice"
      }
    ],
    "half_damage_from": [
      {
        "name": "normal",
        "url": "https://thepokeapi.com/type/normal"
      },
      {
        "name": "flying",
        "url": "https://thepokeapi.com/type/flying"
      },
      {
        "name": "poison",
        "url": "https://thepokeapi.com/type/poison"
      },
      {
        "name": "fire",
        "url": "https://thepokeapi.com/type/fire"
      }
    ],
    "half_damage_to": [
      {
        "name": "fighting",
        "url": "https://thepokeapi.com/type/fighting"
      },
      {
        "name": "ground",
        "url": "https://thepokeapi.com/type/ground"
      },
      {
        "name": "steel",
        "url": "https://thepokeapi.com/type/steel"
      }
    ],
    "no_damage_from": [],
    "no_damage_to": []
  },
  "name": "rock",
  "id": 6,
  "pokemon": [
    {
      "name": "geodude",
      "url": "https://thepokeapi.com/pokemon/geodude",
      "slot": 1
    },
    {
      "name": "graveler",
      "url": "https://thepokeapi.com/pokemon/graveler",
      "slot": 1
    },
    {
      "name": "golem",
      "url": "https://thepokeapi.com/pokemon/golem",
      "slot": 1
    },
    {
      "name": "onix",
      "url": "https://thepokeapi.com/pokemon/onix",
      "slot": 1
    },
    {
      "name": "rhyhorn",
      "url": "https://thepokeapi.com/pokemon/rhyhorn",
      "slot": 2
    },
    {
      "name": "rhydon",
      "url": "https://thepokeapi.com/pokemon/rhydon",
      "slot": 2
    },
    {
      "name": "omanyte",
      "url": "https://thepokeapi.com/pokemon/omanyte",
      "slot": 1
    },
    {
      "name": "omastar",
      "url": "https://thepokeapi.com/pokemon/omastar",
      "slot": 1
    },
    {
      "name": "kabuto",
      "url": "https://thepokeapi.com/pokemon/kabuto",
      "slot": 1
    },
    {
      "name": "kabutops",
      "url": "https://thepokeapi.com/pokemon/kabutops",
      "slot": 1
    },
    {
      "name": "aerodactyl",
      "url": "https://thepokeapi.com/pokemon/aerodactyl",
      "slot": 1
    },
    {
      "name": "sudowoodo",
      "url": "https://thepokeapi.com/pokemon/sudowoodo",
      "slot": 1
    },
    {
      "name": "shuckle",
      "url": "https://thepokeapi.com/pokemon/shuckle",
      "slot": 2
    },
    {
      "name": "magcargo",
      "url": "https://thepokeapi.com/pokemon/magcargo",
      "slot": 2
    },
    {
      "name": "corsola",
      "url": "https://thepokeapi.com/pokemon/corsola",
      "slot": 2
    },
    {
      "name": "larvitar",
      "url": "https://thepokeapi.com/pokemon/larvitar",
      "slot": 1
    },
    {
      "name": "pupitar",
      "url": "https://thepokeapi.com/pokemon/pupitar",
      "slot": 1
    },
    {
      "name": "tyranitar",
      "url": "https://thepokeapi.com/pokemon/tyranitar",
      "slot": 1
    },
    {
      "name": "nosepass",
      "url": "https://thepokeapi.com/pokemon/nosepass",
      "slot": 1
    },
    {
      "name": "aron",
      "url": "https://thepokeapi.com/pokemon/aron",
      "slot": 2
    },
    {
      "name": "lairon",
      "url": "https://thepokeapi.com/pokemon/lairon",
      "slot": 2
    },
    {
      "name": "aggron",
      "url": "https://thepokeapi.com/pokemon/aggron",
      "slot": 2
    },
    {
      "name": "lunatone",
      "url": "https://thepokeapi.com/pokemon/lunatone",
      "slot": 1
    },
    {
      "name": "solrock",
      "url": "https://thepokeapi.com/pokemon/solrock",
      "slot": 1
    },
    {
      "name": "lileep",
      "url": "https://thepokeapi.com/pokemon/lileep",
      "slot": 1
    },
    {
      "name": "cradily",
      "url": "https://thepokeapi.com/pokemon/cradily",
      "slot": 1
    },
    {
      "name": "anorith",
      "url": "https://thepokeapi.com/pokemon/anorith",
      "slot": 1
    },
    {
      "name": "armaldo",
      "url": "https://thepokeapi.com/pokemon/armaldo",
      "slot": 1
    },
    {
      "name": "relicanth",
      "url": "https://thepokeapi.com/pokemon/relicanth",
      "slot": 2
    },
    {
      "name": "regirock",
      "url": "https://thepokeapi.com/pokemon/regirock",
      "slot": 1
    },
    {
      "name": "cranidos",
      "url": "https://thepokeapi.com/pokemon/cranidos",
      "slot": 1
    },
    {
      "name": "rampardos",
      "url": "https://thepokeapi.com/pokemon/rampardos",
      "slot": 1
    },
    {
      "name": "shieldon",
      "url": "https://thepokeapi.com/pokemon/shieldon",
      "slot": 1
    },
    {
      "name": "bastiodon",
      "url": "https://thepokeapi.com/pokemon/bastiodon",
      "slot": 1
    },
    {
      "name": "bonsly",
      "url": "https://thepokeapi.com/pokemon/bonsly",
      "slot": 1
    },
    {
      "name": "rhyperior",
      "url": "https://thepokeapi.com/pokemon/rhyperior",
      "slot": 2
    },
    {
      "name": "probopass",
      "url": "https://thepokeapi.com/pokemon/probopass",
      "slot": 1
    },
    {
      "name": "roggenrola",
      "url": "https://thepokeapi.com/pokemon/roggenrola",
      "slot": 1
    },
    {
      "name": "boldore",
      "url": "https://thepokeapi.com/pokemon/boldore",
      "slot": 1
    },
    {
      "name": "gigalith",
      "url": "https://thepokeapi.com/pokemon/gigalith",
      "slot": 1
    },
    {
      "name": "dwebble",
      "url": "https://thepokeapi.com/pokemon/dwebble",
      "slot": 2
    },
    {
      "name": "crustle",
      "url": "https://thepokeapi.com/pokemon/crustle",
      "slot": 2
    },
    {
      "name": "tirtouga",
      "url": "https://thepokeapi.com/pokemon/tirtouga",
      "slot": 2
    },
    {
      "name": "carracosta",
      "url": "https://thepokeapi.com/pokemon/carracosta",
      "slot": 2
    },
    {
      "name": "archen",
      "url": "https://thepokeapi.com/pokemon/archen",
      "slot": 1
    },
    {
      "name": "archeops",
      "url": "https://thepokeapi.com/pokemon/archeops",
      "slot": 1
    },
    {
      "name": "terrakion",
      "url": "https://thepokeapi.com/pokemon/terrakion",
      "slot": 1
    },
    {
      "name": "binacle",
      "url": "https://thepokeapi.com/pokemon/binacle",
      "slot": 1
    },
    {
      "name": "barbaracle",
      "url": "https://thepokeapi.com/pokemon/barbaracle",
      "slot": 1
    },
    {
      "name": "tyrunt",
      "url": "https://thepokeapi.com/pokemon/tyrunt",
      "slot": 1
    },
    {
      "name": "tyrantrum",
      "url": "https://thepokeapi.com/pokemon/tyrantrum",
      "slot": 1
    },
    {
      "name": "amaura",
      "url": "https://thepokeapi.com/pokemon/amaura",
      "slot": 1
    },
    {
      "name": "aurorus",
      "url": "https://thepokeapi.com/pokemon/aurorus",
      "slot": 1
    },
    {
      "name": "carbink",
      "url": "https://thepokeapi.com/pokemon/carbink",
      "slot": 1
    },
    {
      "name": "diancie",
      "url": "https://thepokeapi.com/pokemon/diancie",
      "slot": 1
    },
    {
      "name": "rockruff",
      "url": "https://thepokeapi.com/pokemon/rockruff",
      "slot": 1
    },
    {
      "name": "nihilego",
      "url": "https://thepokeapi.com/pokemon/nihilego",
      "slot": 1
    },
    {
      "name": "stakataka",
      "url": "https://thepokeapi.com/pokemon/stakataka",
      "slot": 1
    },
    {
      "name": "drednaw",
      "url": "https://thepokeapi.com/pokemon/drednaw",
      "slot": 2
    },
    {
      "name": "rolycoly",
      "url": "https://thepokeapi.com/pokemon/rolycoly",
      "slot": 1
    },
    {
      "name": "carkol",
      "url": "https://thepokeapi.com/pokemon/carkol",
      "slot": 1
    },
    {
      "name": "coalossal",
      "url": "https://thepokeapi.com/pokemon/coalossal",
      "slot": 1
    },
    {
      "name": "stonjourner",
      "url": "https://thepokeapi.com/pokemon/stonjourner",
      "slot": 1
    }
  ]
}

=== hostedposted/PokemonData/data/api/type/ice/index.json
{
  "damage_relations": {
    "double_damage_from": [
      {
        "name": "fighting",
        "url": "https://thepokeapi.com/type/fighting"
      },
      {
        "name": "rock",
        "url": "https://thepokeapi.com/type/rock"
      },
      {
        "name": "steel",
        "url": "https://thepokeapi.com/type/steel"
      },
      {
        "name": "fire",
        "url": "https://thepokeapi.com/type/fire"
      }
    ],
    "double_damage_to": [
      {
        "name": "flying",
        "url": "https://thepokeapi.com/type/flying"
      },
      {
        "name": "ground",
        "url": "https://thepokeapi.com/type/ground"
      },
      {
        "name": "grass",
        "url": "https://thepokeapi.com/type/grass"
      },
      {
        "name": "dragon",
        "url": "https://thepokeapi.com/type/dragon"
      }
    ],
    "half_damage_from": [
      {
        "name": "ice",
        "url": "https://thepokeapi.com/type/ice"
      }
    ],
    "half_damage_to": [
      {
        "name": "steel",
        "url": "https://thepokeapi.com/type/steel"
      },
      {
        "name": "fire",
        "url": "https://thepokeapi.com/type/fire"
      },
      {
        "name": "water",
        "url": "https://thepokeapi.com/type/water"
      },
      {
        "name": "ice",
        "url": "https://thepokeapi.com/type/ice"
      }
    ],
    "no_damage_from": [],
    "no_damage_to": []
  },
  "name": "ice",
  "id": 15,
  "pokemon": [
    {
      "name": "dewgong",
      "url": "https://thepokeapi.com/pokemon/dewgong",
      "slot": 2
    },
    {
      "name": "cloyster",
      "url": "https://thepokeapi.com/pokemon/cloyster",
      "slot": 2
    },
    {
      "name": "jynx",
      "url": "https://thepokeapi.com/pokemon/jynx",
      "slot": 1
    },
    {
      "name": "lapras",
      "url": "https://thepokeapi.com/pokemon/lapras",
      "slot": 2
    },
    {
      "name": "articuno",
      "url": "https://thepokeapi.com/pokemon/articuno",
      "slot": 1
    },
    {
      "name": "sneasel",
      "url": "https://thepokeapi.com/pokemon/sneasel",
      "slot": 2
    },
    {
      "name": "swinub",
      "url": "https://thepokeapi.com/pokemon/swinub",
      "slot": 1
    },
    {
      "name": "piloswine",
      "url": "https://thepokeapi.com/pokemon/piloswine",
      "slot": 1
    },
    {
      "name": "delibird",
      "url": "https://thepokeapi.com/pokemon/delibird",
      "slot": 1
    },
    {
      "name": "smoochum",
      "url": "https://thepokeapi.com/pokemon/smoochum",
      "slot": 1
    },
    {
      "name": "snorunt",
      "url": "https://thepokeapi.com/pokemon/snorunt",
      "slot": 1
    },
    {
      "name": "glalie",
      "url": "https://thepokeapi.com/pokemon/glalie",
      "slot": 1
    },
    {
      "name": "spheal",
      "url": "https://thepokeapi.com/pokemon/spheal",
      "slot": 1
    },
    {
      "name": "sealeo",
      "url": "https://thepokeapi.com/pokemon/sealeo",
      "slot": 1
    },
    {
      "name": "walrein",
      "url": "https://thepokeapi.com/pokemon/walrein",
      "slot": 1
    },
    {
      "name": "regice",
      "url": "https://thepokeapi.com/pokemon/regice",
      "slot": 1
    },
    {
      "name": "snover",
      "url": "https://thepokeapi.com/pokemon/snover",
      "slot": 2
    },
    {
      "name": "abomasnow",
      "url": "https://thepokeapi.com/pokemon/abomasnow",
      "slot": 2
    },
    {
      "name": "weavile",
      "url": "https://thepokeapi.com/pokemon/weavile",
      "slot": 2
    },
    {
      "name": "glaceon",
      "url": "https://thepokeapi.com/pokemon/glaceon",
      "slot": 1
    },
    {
      "name": "mamoswine",
      "url": "https://thepokeapi.com/pokemon/mamoswine",
      "slot": 1
    },
    {
      "name": "froslass",
      "url": "https://thepokeapi.com/pokemon/froslass",
      "slot": 1
    },
    {
      "name": "vanillite",
      "url": "https://thepokeapi.com/pokemon/vanillite",
      "slot": 1
    },
    {
      "name": "vanillish",
      "url": "https://thepokeapi.com/pokemon/vanillish",
      "slot": 1
    },
    {
      "name": "vanilluxe",
      "url": "https://thepokeapi.com/pokemon/vanilluxe",
      "slot": 1
    },
    {
      "name": "cubchoo",
      "url": "https://thepokeapi.com/pokemon/cubchoo",
      "slot": 1
    },
    {
      "name": "beartic",
      "url": "https://thepokeapi.com/pokemon/beartic",
      "slot": 1
    },
    {
      "name": "cryogonal",
      "url": "https://thepokeapi.com/pokemon/cryogonal",
      "slot": 1
    },
    {
      "name": "kyurem",
      "url": "https://thepokeapi.com/pokemon/kyurem",
      "slot": 2
    },
    {
      "name": "amaura",
      "url": "https://thepokeapi.com/pokemon/amaura",
      "slot": 2
    },
    {
      "name": "aurorus",
      "url": "https://thepokeapi.com/pokemon/aurorus",
      "slot": 2
    },
    {
      "name": "bergmite",
      "url": "https://thepokeapi.com/pokemon/bergmite",
      "slot": 1
    },
    {
      "name": "avalugg",
      "url": "https://thepokeapi.com/pokemon/avalugg",
      "slot": 1
    },
    {
      "name": "crabominable",
      "url": "https://thepokeapi.com/pokemon/crabominable",
      "slot": 2
    },
    {
      "name": "snom",
      "url": "https://thepokeapi.com/pokemon/snom",
      "slot": 1
    },
    {
      "name": "frosmoth",
      "url": "https://thepokeapi.com/pokemon/frosmoth",
      "slot": 1
    },
    {
      "name": "arctozolt",
      "url": "https://thepokeapi.com/pokemon/arctozolt",
      "slot": 2
    },
    {
      "name": "arctovish",
      "url": "https://thepokeapi.com/pokemon/arctovish",
      "slot": 2
    },
    {
      "name": "glastrier",
      "url": "https://thepokeapi.com/pokemon/glastrier",
      "slot": 1
    }
  ]
}
