=== hostedposted/PokemonData/data/schema/ability/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "effect": {
      "type": [
        "null",
        "string"
      ]
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "short_effect": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "effect",
    "short_effect"
  ]
}

=== hostedposted/PokemonData/data/api/ability/41/index.json
{
  "description": "Prevents burns.",
  "effect": "This Pok\u00e9mon cannot be burned.\n\nIf a Pok\u00e9mon is burned and acquires this ability, its burn is healed; this includes when regaining a lost ability upon leaving battle.",
  "id": 41,
  "name": "water-veil",
  "pokemon": [
    {
      "name": "goldeen",
      "url": "https://thepokeapi.com/pokemon/goldeen",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "seaking",
      "url": "https://thepokeapi.com/pokemon/seaking",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "mantine",
      "url": "https://thepokeapi.com/pokemon/mantine",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "wailmer",
      "url": "https://thepokeapi.com/pokemon/wailmer",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "wailord",
      "url": "https://thepokeapi.com/pokemon/wailord",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "huntail",
      "url": "https://thepokeapi.com/pokemon/huntail",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "buizel",
      "url": "https://thepokeapi.com/pokemon/buizel",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "floatzel",
      "url": "https://thepokeapi.com/pokemon/floatzel",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "finneon",
      "url": "https://thepokeapi.com/pokemon/finneon",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "lumineon",
      "url": "https://thepokeapi.com/pokemon/lumineon",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "mantyke",
      "url": "https://thepokeapi.com/pokemon/mantyke",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Prevents burns."
}

=== hostedposted/PokemonData/data/api/ability/211/index.json
{
  "description": "Other Cells gather to aid when its HP becomes\nhalf or less. Then the Pok\u00e9mon changes\nits form to Complete Forme.",
  "effect": "Transforms 10% or 50% Zygarde into Complete Forme when its HP is below 50%.\n\nThis ability cannot be copied or replaced.  This ability only takes effect for Zygarde.",
  "id": 211,
  "name": "power-construct",
  "pokemon": [
    {
      "name": "zygarde",
      "url": "https://thepokeapi.com/pokemon/zygarde",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "zygarde",
      "url": "https://thepokeapi.com/pokemon/zygarde",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "zygarde",
      "url": "https://thepokeapi.com/pokemon/zygarde",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Transforms 10% or 50% Zygarde into Complete Forme when its HP is below 50%."
}

=== hostedposted/PokemonData/data/api/ability/rough-skin/index.json
{
  "description": "Hurts to touch.",
  "effect": "Whenever a move makes contact with this Pok\u00e9mon, the move's user takes 1/8 of its maximum HP in damage.\n\nThis ability functions identically to iron barbs.",
  "id": 24,
  "name": "rough-skin",
  "pokemon": [
    {
      "name": "carvanha",
      "url": "https://thepokeapi.com/pokemon/carvanha",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "sharpedo",
      "url": "https://thepokeapi.com/pokemon/sharpedo",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "gible",
      "url": "https://thepokeapi.com/pokemon/gible",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "gabite",
      "url": "https://thepokeapi.com/pokemon/gabite",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "garchomp",
      "url": "https://thepokeapi.com/pokemon/garchomp",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "druddigon",
      "url": "https://thepokeapi.com/pokemon/druddigon",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Damages attacking Pok\u00e9mon for 1/8 their max HP on contact."
}

=== hostedposted/PokemonData/data/api/ability/166/index.json
{
  "description": "\u307f\u304b\u305f\u306e\u3000\u304f\u3055\u30dd\u30b1\u30e2\u30f3\u306f\n\u306e\u3046\u308a\u3087\u304f\u304c\u3000\u3055\u304c\u3089\u306a\u3044\u3002",
  "effect": "Protects friendly grass Pok\u00e9mon from having their stats lowered by other Pok\u00e9mon.",
  "id": 166,
  "name": "flower-veil",
  "pokemon": [
    {
      "name": "flabebe",
      "url": "https://thepokeapi.com/pokemon/flabebe",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "floette",
      "url": "https://thepokeapi.com/pokemon/floette",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "florges",
      "url": "https://thepokeapi.com/pokemon/florges",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "comfey",
      "url": "https://thepokeapi.com/pokemon/comfey",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "floette",
      "url": "https://thepokeapi.com/pokemon/floette",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Protects friendly grass Pok\u00e9mon from having their stats lowered by other Pok\u00e9mon."
}

=== hostedposted/PokemonData/data/api/ability/66/index.json
{
  "description": "Ups FIRE moves in a pinch.",
  "effect": "When this Pok\u00e9mon has 1/3 or less of its HP remaining, its fire-type moves inflict 1.5\u00d7 as much regular damage.",
  "id": 66,
  "name": "blaze",
  "pokemon": [
    {
      "name": "charmander",
      "url": "https://thepokeapi.com/pokemon/charmander",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "charmeleon",
      "url": "https://thepokeapi.com/pokemon/charmeleon",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "charizard",
      "url": "https://thepokeapi.com/pokemon/charizard",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cyndaquil",
      "url": "https://thepokeapi.com/pokemon/cyndaquil",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "quilava",
      "url": "https://thepokeapi.com/pokemon/quilava",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "typhlosion",
      "url": "https://thepokeapi.com/pokemon/typhlosion",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "torchic",
      "url": "https://thepokeapi.com/pokemon/torchic",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "combusken",
      "url": "https://thepokeapi.com/pokemon/combusken",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "blaziken",
      "url": "https://thepokeapi.com/pokemon/blaziken",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "chimchar",
      "url": "https://thepokeapi.com/pokemon/chimchar",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "monferno",
      "url": "https://thepokeapi.com/pokemon/monferno",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "infernape",
      "url": "https://thepokeapi.com/pokemon/infernape",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "tepig",
      "url": "https://thepokeapi.com/pokemon/tepig",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "pignite",
      "url": "https://thepokeapi.com/pokemon/pignite",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "emboar",
      "url": "https://thepokeapi.com/pokemon/emboar",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "pansear",
      "url": "https://thepokeapi.com/pokemon/pansear",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "simisear",
      "url": "https://thepokeapi.com/pokemon/simisear",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "fennekin",
      "url": "https://thepokeapi.com/pokemon/fennekin",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "braixen",
      "url": "https://thepokeapi.com/pokemon/braixen",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "delphox",
      "url": "https://thepokeapi.com/pokemon/delphox",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "litten",
      "url": "https://thepokeapi.com/pokemon/litten",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "torracat",
      "url": "https://thepokeapi.com/pokemon/torracat",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "incineroar",
      "url": "https://thepokeapi.com/pokemon/incineroar",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "scorbunny",
      "url": "https://thepokeapi.com/pokemon/scorbunny",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "raboot",
      "url": "https://thepokeapi.com/pokemon/raboot",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cinderace",
      "url": "https://thepokeapi.com/pokemon/cinderace",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "charizard",
      "url": "https://thepokeapi.com/pokemon/charizard",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cinderace",
      "url": "https://thepokeapi.com/pokemon/cinderace",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Strengthens fire moves to inflict 1.5\u00d7 damage at 1/3 max HP or less."
}

=== hostedposted/PokemonData/data/api/ability/battle-bond/index.json
{
  "description": "Defeating an opposing Pok\u00e9mon strengthens the\nPok\u00e9mon\u2019s bond with its Trainer, and it becomes\nAsh-Greninja. Water Shuriken gets more powerful.",
  "effect": "Transforms this Pok\u00e9mon into Ash-Greninja after fainting an opponent.  Water Shuriken's power is 20 and always hits three times.\n\nThis ability cannot be copied or replaced.  This ability only takes effect for Greninja.",
  "id": 210,
  "name": "battle-bond",
  "pokemon": [
    {
      "name": "greninja",
      "url": "https://thepokeapi.com/pokemon/greninja",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "greninja",
      "url": "https://thepokeapi.com/pokemon/greninja",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Transforms this Pok\u00e9mon into Ash-Greninja after fainting an opponent.  Water Shuriken's power is 20 and always hits three times."
}

=== hostedposted/PokemonData/data/api/ability/no-guard/index.json
{
  "description": "Ensures the Pok\u00e9mon and\nits foe\u2019s attacks land.",
  "effect": "Moves used by or against this Pok\u00e9mon never miss.\n\nOne-hit KO moves are unaffected.  Moves affected by this ability can hit Pok\u00e9mon during the preparation turn of moves like dig or fly.\n\nOverworld: If the lead Pok\u00e9mon has this ability, the wild encounter rate is doubled.",
  "id": 99,
  "name": "no-guard",
  "pokemon": [
    {
      "name": "machop",
      "url": "https://thepokeapi.com/pokemon/machop",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "machoke",
      "url": "https://thepokeapi.com/pokemon/machoke",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "machamp",
      "url": "https://thepokeapi.com/pokemon/machamp",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "karrablast",
      "url": "https://thepokeapi.com/pokemon/karrablast",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "golett",
      "url": "https://thepokeapi.com/pokemon/golett",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "golurk",
      "url": "https://thepokeapi.com/pokemon/golurk",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "honedge",
      "url": "https://thepokeapi.com/pokemon/honedge",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "doublade",
      "url": "https://thepokeapi.com/pokemon/doublade",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "pidgeot",
      "url": "https://thepokeapi.com/pokemon/pidgeot",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "machamp",
      "url": "https://thepokeapi.com/pokemon/machamp",
      "is_hidden": false,
      "slot": 2
    }
  ],
  "short_effect": "Ensures all moves used by and against the Pok\u00e9mon hit."
}

=== hostedposted/PokemonData/data/api/ability/telepathy/index.json
{
  "description": "Anticipates an ally\u2019s\nattack and dodges it.",
  "effect": "This Pok\u00e9mon does not take damage from friendly Pok\u00e9mon's moves, including single-target moves aimed at it.",
  "id": 140,
  "name": "telepathy",
  "pokemon": [
    {
      "name": "wobbuffet",
      "url": "https://thepokeapi.com/pokemon/wobbuffet",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "ralts",
      "url": "https://thepokeapi.com/pokemon/ralts",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "kirlia",
      "url": "https://thepokeapi.com/pokemon/kirlia",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "gardevoir",
      "url": "https://thepokeapi.com/pokemon/gardevoir",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "meditite",
      "url": "https://thepokeapi.com/pokemon/meditite",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "medicham",
      "url": "https://thepokeapi.com/pokemon/medicham",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "wynaut",
      "url": "https://thepokeapi.com/pokemon/wynaut",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "dialga",
      "url": "https://thepokeapi.com/pokemon/dialga",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "palkia",
      "url": "https://thepokeapi.com/pokemon/palkia",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "giratina-altered",
      "url": "https://thepokeapi.com/pokemon/giratina-altered",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "munna",
      "url": "https://thepokeapi.com/pokemon/munna",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "musharna",
      "url": "https://thepokeapi.com/pokemon/musharna",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "elgyem",
      "url": "https://thepokeapi.com/pokemon/elgyem",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "beheeyem",
      "url": "https://thepokeapi.com/pokemon/beheeyem",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "noibat",
      "url": "https://thepokeapi.com/pokemon/noibat",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "noivern",
      "url": "https://thepokeapi.com/pokemon/noivern",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "oranguru",
      "url": "https://thepokeapi.com/pokemon/oranguru",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "tapu-koko",
      "url": "https://thepokeapi.com/pokemon/tapu-koko",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "tapu-lele",
      "url": "https://thepokeapi.com/pokemon/tapu-lele",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "tapu-bulu",
      "url": "https://thepokeapi.com/pokemon/tapu-bulu",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "tapu-fini",
      "url": "https://thepokeapi.com/pokemon/tapu-fini",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "blipbug",
      "url": "https://thepokeapi.com/pokemon/blipbug",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "dottler",
      "url": "https://thepokeapi.com/pokemon/dottler",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "orbeetle",
      "url": "https://thepokeapi.com/pokemon/orbeetle",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "orbeetle",
      "url": "https://thepokeapi.com/pokemon/orbeetle",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Protects against friendly Pok\u00e9mon's damaging moves."
}
