=== hostedposted/PokemonData/data/schema/ability/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "effect": {
      "type": [
        "null",
        "string"
      ]
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "short_effect": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "effect",
    "short_effect"
  ]
}

=== hostedposted/PokemonData/data/api/ability/corrosion/index.json
{
  "description": "\uac15\ucca0\ud0c0\uc785\uc774\ub098 \ub3c5\ud0c0\uc785\ub3c4\n\ub3c5 \uc0c1\ud0dc\ub85c \ub9cc\ub4e4 \uc218 \uc788\ub2e4.",
  "effect": "This Pok\u00e9mon's moves and item ignore the usual immunity of Poison and Steel Pok\u00e9mon when attempting to inflict poison.",
  "id": 212,
  "name": "corrosion",
  "pokemon": [
    {
      "name": "salandit",
      "url": "https://thepokeapi.com/pokemon/salandit",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "salazzle",
      "url": "https://thepokeapi.com/pokemon/salazzle",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "salazzle",
      "url": "https://thepokeapi.com/pokemon/salazzle",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "This Pok\u00e9mon can inflict poison on Poison and Steel Pok\u00e9mon."
}

=== hostedposted/PokemonData/data/api/ability/47/index.json
{
  "description": "Heat-and-cold protection.",
  "effect": "This Pok\u00e9mon takes half as much damage from fire- and ice-type moves.",
  "id": 47,
  "name": "thick-fat",
  "pokemon": [
    {
      "name": "seel",
      "url": "https://thepokeapi.com/pokemon/seel",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "dewgong",
      "url": "https://thepokeapi.com/pokemon/dewgong",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "snorlax",
      "url": "https://thepokeapi.com/pokemon/snorlax",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "marill",
      "url": "https://thepokeapi.com/pokemon/marill",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "azumarill",
      "url": "https://thepokeapi.com/pokemon/azumarill",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "swinub",
      "url": "https://thepokeapi.com/pokemon/swinub",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "piloswine",
      "url": "https://thepokeapi.com/pokemon/piloswine",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "miltank",
      "url": "https://thepokeapi.com/pokemon/miltank",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "makuhita",
      "url": "https://thepokeapi.com/pokemon/makuhita",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "hariyama",
      "url": "https://thepokeapi.com/pokemon/hariyama",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "azurill",
      "url": "https://thepokeapi.com/pokemon/azurill",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "spoink",
      "url": "https://thepokeapi.com/pokemon/spoink",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "grumpig",
      "url": "https://thepokeapi.com/pokemon/grumpig",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "spheal",
      "url": "https://thepokeapi.com/pokemon/spheal",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "sealeo",
      "url": "https://thepokeapi.com/pokemon/sealeo",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "walrein",
      "url": "https://thepokeapi.com/pokemon/walrein",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "purugly",
      "url": "https://thepokeapi.com/pokemon/purugly",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "munchlax",
      "url": "https://thepokeapi.com/pokemon/munchlax",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "mamoswine",
      "url": "https://thepokeapi.com/pokemon/mamoswine",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "tepig",
      "url": "https://thepokeapi.com/pokemon/tepig",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "pignite",
      "url": "https://thepokeapi.com/pokemon/pignite",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "appletun",
      "url": "https://thepokeapi.com/pokemon/appletun",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "venusaur",
      "url": "https://thepokeapi.com/pokemon/venusaur",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "rattata",
      "url": "https://thepokeapi.com/pokemon/rattata",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "snorlax",
      "url": "https://thepokeapi.com/pokemon/snorlax",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "appletun",
      "url": "https://thepokeapi.com/pokemon/appletun",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Halves damage from fire and ice moves."
}

=== hostedposted/PokemonData/data/api/ability/224/index.json
{
  "description": "The Pok\u00e9mon boosts its most proficient stat each\ntime it knocks out a Pok\u00e9mon.",
  "effect": "Raises this Pok\u00e9mon's highest stat by one stage when it faints another Pok\u00e9mon.",
  "id": 224,
  "name": "beast-boost",
  "pokemon": [
    {
      "name": "nihilego",
      "url": "https://thepokeapi.com/pokemon/nihilego",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "buzzwole",
      "url": "https://thepokeapi.com/pokemon/buzzwole",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "pheromosa",
      "url": "https://thepokeapi.com/pokemon/pheromosa",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "xurkitree",
      "url": "https://thepokeapi.com/pokemon/xurkitree",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "celesteela",
      "url": "https://thepokeapi.com/pokemon/celesteela",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "kartana",
      "url": "https://thepokeapi.com/pokemon/kartana",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "guzzlord",
      "url": "https://thepokeapi.com/pokemon/guzzlord",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "poipole",
      "url": "https://thepokeapi.com/pokemon/poipole",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "naganadel",
      "url": "https://thepokeapi.com/pokemon/naganadel",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "stakataka",
      "url": "https://thepokeapi.com/pokemon/stakataka",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "blacephalon",
      "url": "https://thepokeapi.com/pokemon/blacephalon",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Raises this Pok\u00e9mon's highest stat by one stage when it faints another Pok\u00e9mon."
}

=== hostedposted/PokemonData/data/api/ability/116/index.json
{
  "description": "Powers down super\u00ad\neffective moves.",
  "effect": "This Pok\u00e9mon takes 0.75\u00d7 as much damage from moves that are super effective against it.\n\nThis ability functions identically to filter.",
  "id": 116,
  "name": "solid-rock",
  "pokemon": [
    {
      "name": "camerupt",
      "url": "https://thepokeapi.com/pokemon/camerupt",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "rhyperior",
      "url": "https://thepokeapi.com/pokemon/rhyperior",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "tirtouga",
      "url": "https://thepokeapi.com/pokemon/tirtouga",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "carracosta",
      "url": "https://thepokeapi.com/pokemon/carracosta",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Decreases damage taken from super-effective moves by 1/4."
}

=== hostedposted/PokemonData/data/api/ability/tinted-lens/index.json
{
  "description": "Powers up \u201cnot very\neffective\u201d moves.",
  "effect": "This Pok\u00e9mon deals twice as much damage with moves that are not very effective against the target.",
  "id": 110,
  "name": "tinted-lens",
  "pokemon": [
    {
      "name": "butterfree",
      "url": "https://thepokeapi.com/pokemon/butterfree",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "venonat",
      "url": "https://thepokeapi.com/pokemon/venonat",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "venomoth",
      "url": "https://thepokeapi.com/pokemon/venomoth",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "hoothoot",
      "url": "https://thepokeapi.com/pokemon/hoothoot",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "noctowl",
      "url": "https://thepokeapi.com/pokemon/noctowl",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "illumise",
      "url": "https://thepokeapi.com/pokemon/illumise",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "mothim",
      "url": "https://thepokeapi.com/pokemon/mothim",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "yanmega",
      "url": "https://thepokeapi.com/pokemon/yanmega",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "sigilyph",
      "url": "https://thepokeapi.com/pokemon/sigilyph",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "butterfree",
      "url": "https://thepokeapi.com/pokemon/butterfree",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Doubles damage inflicted with not-very-effective moves."
}

=== hostedposted/PokemonData/data/api/ability/93/index.json
{
  "description": "Heals status problems if\nit is raining.",
  "effect": "This Pok\u00e9mon is cured of any major status ailment after each turn during rain.",
  "id": 93,
  "name": "hydration",
  "pokemon": [
    {
      "name": "seel",
      "url": "https://thepokeapi.com/pokemon/seel",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "dewgong",
      "url": "https://thepokeapi.com/pokemon/dewgong",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "lapras",
      "url": "https://thepokeapi.com/pokemon/lapras",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "vaporeon",
      "url": "https://thepokeapi.com/pokemon/vaporeon",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "smoochum",
      "url": "https://thepokeapi.com/pokemon/smoochum",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "wingull",
      "url": "https://thepokeapi.com/pokemon/wingull",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "barboach",
      "url": "https://thepokeapi.com/pokemon/barboach",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "whiscash",
      "url": "https://thepokeapi.com/pokemon/whiscash",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "gorebyss",
      "url": "https://thepokeapi.com/pokemon/gorebyss",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "luvdisc",
      "url": "https://thepokeapi.com/pokemon/luvdisc",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "phione",
      "url": "https://thepokeapi.com/pokemon/phione",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "manaphy",
      "url": "https://thepokeapi.com/pokemon/manaphy",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "tympole",
      "url": "https://thepokeapi.com/pokemon/tympole",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "palpitoad",
      "url": "https://thepokeapi.com/pokemon/palpitoad",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "ducklett",
      "url": "https://thepokeapi.com/pokemon/ducklett",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "swanna",
      "url": "https://thepokeapi.com/pokemon/swanna",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "alomomola",
      "url": "https://thepokeapi.com/pokemon/alomomola",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "shelmet",
      "url": "https://thepokeapi.com/pokemon/shelmet",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "accelgor",
      "url": "https://thepokeapi.com/pokemon/accelgor",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "goomy",
      "url": "https://thepokeapi.com/pokemon/goomy",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "sliggoo",
      "url": "https://thepokeapi.com/pokemon/sliggoo",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "goodra",
      "url": "https://thepokeapi.com/pokemon/goodra",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "lapras",
      "url": "https://thepokeapi.com/pokemon/lapras",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Cures any major status ailment after each turn during rain."
}

=== hostedposted/PokemonData/data/api/ability/cute-charm/index.json
{
  "description": "Infatuates on contact.",
  "effect": "Whenever a move makes contact with this Pok\u00e9mon, the move's user has a 30% chance of being infatuated.\n\nOverworld: If the first Pok\u00e9mon in the party has this ability, any wild Pok\u00e9mon whose species can be either gender has a 2/3 chance of being set to the opposite gender, and a 1/3 chance of having a random gender as usual.",
  "id": 56,
  "name": "cute-charm",
  "pokemon": [
    {
      "name": "clefairy",
      "url": "https://thepokeapi.com/pokemon/clefairy",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "clefable",
      "url": "https://thepokeapi.com/pokemon/clefable",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "jigglypuff",
      "url": "https://thepokeapi.com/pokemon/jigglypuff",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "wigglytuff",
      "url": "https://thepokeapi.com/pokemon/wigglytuff",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cleffa",
      "url": "https://thepokeapi.com/pokemon/cleffa",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "igglybuff",
      "url": "https://thepokeapi.com/pokemon/igglybuff",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "skitty",
      "url": "https://thepokeapi.com/pokemon/skitty",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "delcatty",
      "url": "https://thepokeapi.com/pokemon/delcatty",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "milotic",
      "url": "https://thepokeapi.com/pokemon/milotic",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "lopunny",
      "url": "https://thepokeapi.com/pokemon/lopunny",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "minccino",
      "url": "https://thepokeapi.com/pokemon/minccino",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cinccino",
      "url": "https://thepokeapi.com/pokemon/cinccino",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "sylveon",
      "url": "https://thepokeapi.com/pokemon/sylveon",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "stufful",
      "url": "https://thepokeapi.com/pokemon/stufful",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Has a 30% chance of infatuating attacking Pok\u00e9mon on contact."
}

=== hostedposted/PokemonData/data/api/ability/195/index.json
{
  "description": "Boosts the Pok\u00e9mon\u2019s Defense stat sharply when hit\nby a Water-type move.",
  "effect": "Raises this Pok\u00e9mon's Defense by two stages when it's hit by a Water move.",
  "id": 195,
  "name": "water-compaction",
  "pokemon": [
    {
      "name": "sandygast",
      "url": "https://thepokeapi.com/pokemon/sandygast",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "palossand",
      "url": "https://thepokeapi.com/pokemon/palossand",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Raises this Pok\u00e9mon's Defense by two stages when it's hit by a Water move."
}
