=== hostedposted/PokemonData/data/schema/ability/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "effect": {
      "type": [
        "null",
        "string"
      ]
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          }
        },
        "required": [
          "is_hidden",
          "name",
          "slot",
          "url"
        ]
      }
    },
    "short_effect": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "effect",
    "short_effect"
  ]
}

=== hostedposted/PokemonData/data/api/ability/212/index.json
{
  "description": "The Pok\u00e9mon can poison the target even if it\u2019s\na Steel or Poison type.",
  "effect": "This Pok\u00e9mon's moves and item ignore the usual immunity of Poison and Steel Pok\u00e9mon when attempting to inflict poison.",
  "id": 212,
  "name": "corrosion",
  "pokemon": [
    {
      "name": "salandit",
      "url": "https://thepokeapi.com/pokemon/salandit",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "salazzle",
      "url": "https://thepokeapi.com/pokemon/salazzle",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "salazzle",
      "url": "https://thepokeapi.com/pokemon/salazzle",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "This Pok\u00e9mon can inflict poison on Poison and Steel Pok\u00e9mon."
}

=== hostedposted/PokemonData/data/api/ability/217/index.json
{
  "description": "\u307f\u304b\u305f\u306e\u3000\u3068\u304f\u3057\u3085\u308f\u3056\u306e\n\u3044\u308a\u3087\u304f\u3092\u3000\u3042\u3052\u308b\u3002",
  "effect": "Ally Pok\u00e9mon's moves have their power increased to 1.3\u00d7.",
  "id": 217,
  "name": "battery",
  "pokemon": [
    {
      "name": "charjabug",
      "url": "https://thepokeapi.com/pokemon/charjabug",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Ally Pok\u00e9mon's moves have their power increased to 1.3\u00d7."
}

=== hostedposted/PokemonData/data/api/ability/205/index.json
{
  "description": "Gives priority to a healing move.",
  "effect": "This Pok\u00e9mon's healing moves have their priority increased by 3.",
  "id": 205,
  "name": "triage",
  "pokemon": [
    {
      "name": "comfey",
      "url": "https://thepokeapi.com/pokemon/comfey",
      "is_hidden": false,
      "slot": 2
    }
  ],
  "short_effect": "This Pok\u00e9mon's healing moves have their priority increased by 3."
}

=== hostedposted/PokemonData/data/api/ability/effect-spore/index.json
{
  "description": "Leaves spores on contact.",
  "effect": "Whenever a move makes contact with this Pok\u00e9mon, the move's user has a 30% chance of being paralyzed, poisoned, or put to sleep, chosen at random.\n\nNothing is done to compensate if the move's user is immune to one of these ailments; there is simply a lower chance that the move's user will be affected.",
  "id": 27,
  "name": "effect-spore",
  "pokemon": [
    {
      "name": "vileplume",
      "url": "https://thepokeapi.com/pokemon/vileplume",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "paras",
      "url": "https://thepokeapi.com/pokemon/paras",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "parasect",
      "url": "https://thepokeapi.com/pokemon/parasect",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "shroomish",
      "url": "https://thepokeapi.com/pokemon/shroomish",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "breloom",
      "url": "https://thepokeapi.com/pokemon/breloom",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "foongus",
      "url": "https://thepokeapi.com/pokemon/foongus",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "amoonguss",
      "url": "https://thepokeapi.com/pokemon/amoonguss",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "morelull",
      "url": "https://thepokeapi.com/pokemon/morelull",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "shiinotic",
      "url": "https://thepokeapi.com/pokemon/shiinotic",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "gossifleur",
      "url": "https://thepokeapi.com/pokemon/gossifleur",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "eldegoss",
      "url": "https://thepokeapi.com/pokemon/eldegoss",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pok\u00e9mon on contact."
}

=== hostedposted/PokemonData/data/api/ability/water-absorb/index.json
{
  "description": "\u307f\u305a\u3092\u3000\u53d7\u3051\u308b\u3068\n\u56de\u5fa9\u3059\u308b\u3002",
  "effect": "Whenever a water-type move hits this Pok\u00e9mon, it heals for 1/4 of its maximum HP, negating any other effect on it.\n\nWater moves will ignore this Pok\u00e9mon's substitute.",
  "id": 11,
  "name": "water-absorb",
  "pokemon": [
    {
      "name": "poliwag",
      "url": "https://thepokeapi.com/pokemon/poliwag",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "poliwhirl",
      "url": "https://thepokeapi.com/pokemon/poliwhirl",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "poliwrath",
      "url": "https://thepokeapi.com/pokemon/poliwrath",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "lapras",
      "url": "https://thepokeapi.com/pokemon/lapras",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "vaporeon",
      "url": "https://thepokeapi.com/pokemon/vaporeon",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "chinchou",
      "url": "https://thepokeapi.com/pokemon/chinchou",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "lanturn",
      "url": "https://thepokeapi.com/pokemon/lanturn",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "politoed",
      "url": "https://thepokeapi.com/pokemon/politoed",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "wooper",
      "url": "https://thepokeapi.com/pokemon/wooper",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "quagsire",
      "url": "https://thepokeapi.com/pokemon/quagsire",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "mantine",
      "url": "https://thepokeapi.com/pokemon/mantine",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "cacnea",
      "url": "https://thepokeapi.com/pokemon/cacnea",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "cacturne",
      "url": "https://thepokeapi.com/pokemon/cacturne",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "mantyke",
      "url": "https://thepokeapi.com/pokemon/mantyke",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "tympole",
      "url": "https://thepokeapi.com/pokemon/tympole",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "palpitoad",
      "url": "https://thepokeapi.com/pokemon/palpitoad",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "seismitoad",
      "url": "https://thepokeapi.com/pokemon/seismitoad",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "maractus",
      "url": "https://thepokeapi.com/pokemon/maractus",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "frillish",
      "url": "https://thepokeapi.com/pokemon/frillish",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "jellicent",
      "url": "https://thepokeapi.com/pokemon/jellicent",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "volcanion",
      "url": "https://thepokeapi.com/pokemon/volcanion",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "dewpider",
      "url": "https://thepokeapi.com/pokemon/dewpider",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "araquanid",
      "url": "https://thepokeapi.com/pokemon/araquanid",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "dracovish",
      "url": "https://thepokeapi.com/pokemon/dracovish",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "arctovish",
      "url": "https://thepokeapi.com/pokemon/arctovish",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "araquanid",
      "url": "https://thepokeapi.com/pokemon/araquanid",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "lapras",
      "url": "https://thepokeapi.com/pokemon/lapras",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Absorbs water moves, healing for 1/4 max HP."
}

=== hostedposted/PokemonData/data/api/ability/clear-body/index.json
{
  "description": "Prevents ability reduction.",
  "effect": "This Pok\u00e9mon cannot have its stats lowered by other Pok\u00e9mon.\n\nThis ability does not prevent any stat losses other than stat modifiers, such as the Speed cut from paralysis.  This Pok\u00e9mon can still be passed negative stat modifiers through guard swap, heart swap, or power swap.\n\nThis ability functions identically to white smoke in battle.",
  "id": 29,
  "name": "clear-body",
  "pokemon": [
    {
      "name": "tentacool",
      "url": "https://thepokeapi.com/pokemon/tentacool",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "tentacruel",
      "url": "https://thepokeapi.com/pokemon/tentacruel",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "beldum",
      "url": "https://thepokeapi.com/pokemon/beldum",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "metang",
      "url": "https://thepokeapi.com/pokemon/metang",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "metagross",
      "url": "https://thepokeapi.com/pokemon/metagross",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "regirock",
      "url": "https://thepokeapi.com/pokemon/regirock",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "regice",
      "url": "https://thepokeapi.com/pokemon/regice",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "registeel",
      "url": "https://thepokeapi.com/pokemon/registeel",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "klink",
      "url": "https://thepokeapi.com/pokemon/klink",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "klang",
      "url": "https://thepokeapi.com/pokemon/klang",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "klinklang",
      "url": "https://thepokeapi.com/pokemon/klinklang",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "carbink",
      "url": "https://thepokeapi.com/pokemon/carbink",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "diancie",
      "url": "https://thepokeapi.com/pokemon/diancie",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "dreepy",
      "url": "https://thepokeapi.com/pokemon/dreepy",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "drakloak",
      "url": "https://thepokeapi.com/pokemon/drakloak",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "dragapult",
      "url": "https://thepokeapi.com/pokemon/dragapult",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Prevents stats from being lowered by other Pok\u00e9mon."
}

=== hostedposted/PokemonData/data/api/ability/55/index.json
{
  "description": "Trades accuracy for power.",
  "effect": "This Pok\u00e9mon's physical moves do 1.5\u00d7 as much regular damage, but have 0.8\u00d7 their usual accuracy.\n\nSpecial moves are unaffected.  Moves that do set damage, such as seismic toss, have their accuracy affected, but not their damage.\n\nOverworld: If the lead Pok\u00e9mon has this ability, higher-levelled Pok\u00e9mon have their encounter rate increased.",
  "id": 55,
  "name": "hustle",
  "pokemon": [
    {
      "name": "rattata",
      "url": "https://thepokeapi.com/pokemon/rattata",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "nidoran-f",
      "url": "https://thepokeapi.com/pokemon/nidoran-f",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "nidorina",
      "url": "https://thepokeapi.com/pokemon/nidorina",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "nidoran-m",
      "url": "https://thepokeapi.com/pokemon/nidoran-m",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "nidorino",
      "url": "https://thepokeapi.com/pokemon/nidorino",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "togepi",
      "url": "https://thepokeapi.com/pokemon/togepi",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "togetic",
      "url": "https://thepokeapi.com/pokemon/togetic",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "corsola",
      "url": "https://thepokeapi.com/pokemon/corsola",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "remoraid",
      "url": "https://thepokeapi.com/pokemon/remoraid",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "delibird",
      "url": "https://thepokeapi.com/pokemon/delibird",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "combee",
      "url": "https://thepokeapi.com/pokemon/combee",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "togekiss",
      "url": "https://thepokeapi.com/pokemon/togekiss",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "darumaka",
      "url": "https://thepokeapi.com/pokemon/darumaka",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "rufflet",
      "url": "https://thepokeapi.com/pokemon/rufflet",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "durant",
      "url": "https://thepokeapi.com/pokemon/durant",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "deino",
      "url": "https://thepokeapi.com/pokemon/deino",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "zweilous",
      "url": "https://thepokeapi.com/pokemon/zweilous",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "flapple",
      "url": "https://thepokeapi.com/pokemon/flapple",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "dracozolt",
      "url": "https://thepokeapi.com/pokemon/dracozolt",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "rattata",
      "url": "https://thepokeapi.com/pokemon/rattata",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "raticate",
      "url": "https://thepokeapi.com/pokemon/raticate",
      "is_hidden": false,
      "slot": 2
    },
    {
      "name": "darumaka",
      "url": "https://thepokeapi.com/pokemon/darumaka",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "flapple",
      "url": "https://thepokeapi.com/pokemon/flapple",
      "is_hidden": true,
      "slot": 3
    }
  ],
  "short_effect": "Strengthens physical moves to inflict 1.5\u00d7 damage, but decreases their accuracy to 0.8\u00d7."
}

=== hostedposted/PokemonData/data/api/ability/175/index.json
{
  "description": "\u307f\u304b\u305f\u306e\u3000\u30dd\u30b1\u30e2\u30f3\u306f\n\u306d\u3080\u3089\u306a\u304f\u306a\u308b\u3002",
  "effect": "Prevents friendly Pok\u00e9mon from sleeping.",
  "id": 175,
  "name": "sweet-veil",
  "pokemon": [
    {
      "name": "swirlix",
      "url": "https://thepokeapi.com/pokemon/swirlix",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "slurpuff",
      "url": "https://thepokeapi.com/pokemon/slurpuff",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "cutiefly",
      "url": "https://thepokeapi.com/pokemon/cutiefly",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "ribombee",
      "url": "https://thepokeapi.com/pokemon/ribombee",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "bounsweet",
      "url": "https://thepokeapi.com/pokemon/bounsweet",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "steenee",
      "url": "https://thepokeapi.com/pokemon/steenee",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "tsareena",
      "url": "https://thepokeapi.com/pokemon/tsareena",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "milcery",
      "url": "https://thepokeapi.com/pokemon/milcery",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "alcremie",
      "url": "https://thepokeapi.com/pokemon/alcremie",
      "is_hidden": false,
      "slot": 1
    },
    {
      "name": "ribombee",
      "url": "https://thepokeapi.com/pokemon/ribombee",
      "is_hidden": true,
      "slot": 3
    },
    {
      "name": "alcremie",
      "url": "https://thepokeapi.com/pokemon/alcremie",
      "is_hidden": false,
      "slot": 1
    }
  ],
  "short_effect": "Prevents friendly Pok\u00e9mon from sleeping."
}
